// components/swap/AdSlot.vue
<!-- Placeholder schermata pubblicitaria — da collegare a AdMob/AdSense in produzione -->
<script setup lang="ts">
defineEmits<{ close: [] }>()
</script>

<template>
  <div style="position:fixed;inset:0;z-index:350;background:rgba(3,2,12,0.97);backdrop-filter:blur(16px);display:flex;flex-direction:column;align-items:center;justify-content:center;padding:32px">
    <div style="font-family:var(--ff-label,'Saira Condensed',sans-serif);font-size:9px;letter-spacing:0.2em;color:rgba(174,156,255,0.4);text-transform:uppercase;margin-bottom:20px">
      Pubblicità
    </div>
    <div style="width:100%;max-width:320px;aspect-ratio:4/3;background:rgba(255,255,255,0.04);border:1px dashed rgba(174,156,255,0.15);border-radius:16px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;margin-bottom:24px">
      <div style="font-size:40px;opacity:0.3">📢</div>
      <div style="font-family:var(--ff-label,'Saira Condensed',sans-serif);font-size:10px;color:rgba(241,235,255,0.2);letter-spacing:0.15em;text-transform:uppercase">
        Spazio pubblicitario
      </div>
    </div>
    <button @click="$emit('close')" style="padding:12px 32px;background:rgba(255,255,255,0.06);border:1px solid rgba(174,156,255,0.2);border-radius:12px;color:rgba(241,235,255,0.7);font-family:var(--ff-label,'Saira Condensed',sans-serif);font-size:11px;letter-spacing:0.18em;text-transform:uppercase;cursor:pointer">
      Continua →
    </button>
  </div>
</template>

// src/components/swap/AdSlot.jsx
'use client';
import { C, FF } from '@/app/gioco/_redesign/_shared';

// Placeholder per annunci pubblicitari — da collegare a AdMob/AdSense in produzione
export default function AdSlot({ onClose }) {
  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 350,
      background: 'rgba(3,2,12,0.97)', backdropFilter: 'blur(16px)',
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: 32,
    }}>
      <div style={{ fontFamily: FF.label, fontSize: 9, letterSpacing: '0.2em', color: 'rgba(174,156,255,0.4)', textTransform: 'uppercase', marginBottom: 20 }}>
        Pubblicità
      </div>

      {/* Ad placeholder */}
      <div style={{
        width: '100%', maxWidth: 320, aspectRatio: '4/3',
        background: 'rgba(255,255,255,0.04)', border: '1px dashed rgba(174,156,255,0.15)',
        borderRadius: 16, display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 24,
      }}>
        <div style={{ fontSize: 40, opacity: 0.3 }}>📢</div>
        <div style={{ fontFamily: FF.label, fontSize: 10, color: 'rgba(241,235,255,0.2)', letterSpacing: '0.15em', textTransform: 'uppercase' }}>
          Spazio pubblicitario
        </div>
      </div>

      <button onClick={onClose} style={{
        padding: '12px 32px',
        background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(174,156,255,0.2)',
        borderRadius: 12, color: 'rgba(241,235,255,0.7)',
        fontFamily: FF.label, fontSize: 11, letterSpacing: '0.18em',
        textTransform: 'uppercase', cursor: 'pointer',
      }}>
        Continua →
      </button>
    </div>
  );
}
