// components/mappa/BattleModal.vue
<!-- BattleModal — Selezione team (preset o manuale) prima di avviare la battaglia su un pixel. -->
<!-- Porta BattleModal.jsx: mostra team salvati o selezione waifu con paginazione e filtri. -->
<script setup lang="ts">
// Icone Lucide — X per chiudi, Swords per battaglia, Zap per velocità
import { X, Swords, Zap } from 'lucide-vue-next'
import { useAuthStore } from '~/stores/auth'
import { RARITA } from '~/utils/constants'

// ── Costanti locali (da _shared.jsx) ─────────────────────────────────────────
const C = {
  violet: '#a78bfa',
  sakura: '#ff85b6',
  gold:   '#ffc861',
  aqua:   '#5ee7df',
  err:    '#ff5b6c',
}
const FF = {
  label:   "var(--ff-label, 'Saira Condensed', sans-serif)",
  display: "var(--ff-display, 'Unbounded', sans-serif)",
  body:    "var(--ff-body, 'DM Sans', sans-serif)",
  mono:    "var(--ff-mono, 'JetBrains Mono', monospace)",
}

const PAGE_SIZE = 12
const RARITY_ORDER = ['comune', 'raro', 'epico', 'leggendario', 'immersivo']

// Colori per tipo elemento
const TYPE_COLORS: Record<string, string> = {
  Fuoco:  '#ff6b35', Acqua:  '#5aa9ff', Natura: '#16a34a',
  Arcana: '#b573ff', Abisso: '#6b7aff', Ferro:  '#b4bcc8',
  Terra:  '#c8a46e', Luce:   '#ffe066', Ombra:  '#8877bb',
}

// ── Props ed emits ────────────────────────────────────────────────────────────
const props = defineProps<{
  pixel?:     Record<string, any> | null
  collezione?: Record<string, any> | null
  waifuCat?:  any[]
  mosseCat?:  any[]
}>()

// Lookup mossa dal catalogo per ID
function getMossa(id: string | null | undefined): { nome: string; tipologia: string } | null {
  if (!id) return null
  return props.mosseCat?.find((m: any) => m.id === id) ?? null
}

const emit = defineEmits<{
  /** Conferma selezione: array di 5 id waifu */
  conferma: [team: any[]]
  /** Chiude il modal */
  chiudi: []
}>()

// ── Auth + tema ───────────────────────────────────────────────────────────────
const authStore  = useAuthStore()
const { isDark } = useTheme()
// Oro leggibile su entrambi i temi (light leggermente più chiaro del precedente)
const gold       = computed(() => isDark.value ? '#ffc861' : '#D4A000')
// Card non selezionata: grigio più marcato in light mode
const cardBg     = computed(() => isDark.value ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.07)')
const cardBorder = computed(() => isDark.value ? 'rgba(174,156,255,0.20)' : 'rgba(0,0,0,0.18)')

// Colore tipo mossa — sovrascrive i toni chiari (Ferro/Luce) in light mode
function moveTypeColor(tipologia: string): string {
  if (!isDark.value) {
    const overrides: Record<string, string> = { Ferro: '#374151', Luce: '#4B5563' }
    return overrides[tipologia] ?? TYPE_COLORS[tipologia] ?? '#888'
  }
  return TYPE_COLORS[tipologia] ?? '#888'
}

// ── Scroll lock (statico: sempre attivo quando il componente è montato) ───────
useScrollLock(true)

// ── Stato ─────────────────────────────────────────────────────────────────────
const teams   = computed(() => props.collezione?.teams ?? {})
const presets = computed(() =>
  Object.entries(teams.value).filter(([, t]: [string, any]) => t.waifu?.length === 5)
)
const hasTeams = computed(() => presets.value.length > 0)

// mode: 'teams' (default se ho team) | 'manual'
const mode           = ref<'teams' | 'manual'>(hasTeams.value ? 'teams' : 'manual')
const selectedIds    = ref<string[]>([])
const activePresetId = ref<string | null>(null)

// Stato caricamento immagini carte: spinner finché l'immagine non è pronta
const loadedImgs = ref(new Set<string>())
function markImgLoaded(id: string) { loadedImgs.value.add(id) }

// Paginazione e filtri (solo in modalità manual)
const page         = ref(0)
const filterRarity = ref('')
const filterType   = ref('')
const sortBy       = ref<'rarita' | 'velocita' | 'crit'>('rarita')

// Colori rarità
const rarColors: Record<string, string> = {
  comune:      '#b4bcc8',
  raro:        '#5aa9ff',
  epico:       '#b573ff',
  leggendario: '#ffc861',
  immersivo:   '#ff7eb6',
}

// ── Computed: waifu possedute con almeno 4 mosse assegnate ───────────────────
const ownedWaifu = computed(() => {
  const list = Object.entries(props.collezione?.waifu ?? {})
    .map(([id, dati]: [string, any]) => {
      const w = props.waifuCat?.find((x: any) => x.id === id)
      if (!w) return null
      const mosseAssegnate = Object.values(dati.mosse_slot ?? {}).filter(Boolean).length
      if (mosseAssegnate < 4) return null
      return { ...w, ...dati, _datiColl: dati }
    })
    .filter(Boolean)

  if (sortBy.value === 'rarita')    list.sort((a: any, b: any) => RARITY_ORDER.indexOf(b.rarita) - RARITY_ORDER.indexOf(a.rarita))
  else if (sortBy.value === 'velocita') list.sort((a: any, b: any) => (b.battleStats?.speed ?? 0) - (a.battleStats?.speed ?? 0))
  else if (sortBy.value === 'crit') list.sort((a: any, b: any) => (b.battleStats?.critChance ?? 0) - (a.battleStats?.critChance ?? 0))

  return list as any[]
})

const filtered = computed(() =>
  ownedWaifu.value.filter((w: any) => {
    if (filterRarity.value && w.rarita?.toLowerCase() !== filterRarity.value.toLowerCase()) return false
    if (filterType.value && w.tipo !== filterType.value && w.battleStats?.type !== filterType.value) return false
    return true
  })
)

const totalPages = computed(() => Math.ceil(filtered.value.length / PAGE_SIZE))
const pageWaifu  = computed(() =>
  filtered.value.slice(page.value * PAGE_SIZE, (page.value + 1) * PAGE_SIZE)
)

// Loading globale: pronto quando TUTTE le immagini della pagina corrente sono caricate
const imagesReady = computed(() =>
  pageWaifu.value.every(w =>
    !(w.asset_immagine || w.asset_statica || w.asset_immersiva) || loadedImgs.value.has(w.id),
  ),
)

// ── Azioni ────────────────────────────────────────────────────────────────────
function toggle(id: string) {
  activePresetId.value = null
  if (selectedIds.value.includes(id)) {
    selectedIds.value = selectedIds.value.filter(x => x !== id)
  } else if (selectedIds.value.length < 8) {   // pool max 8
    selectedIds.value = [...selectedIds.value, id]
  }
}

function selectPreset(id: string, presetWaifu: string[]) {
  const valid = presetWaifu.filter(wid => ownedWaifu.value.some((w: any) => w.id === wid))
  if (valid.length === 5) {
    selectedIds.value    = valid
    activePresetId.value = id
  }
}

function setManual() {
  mode.value           = 'manual'
  selectedIds.value    = []
  activePresetId.value = null
}

function setTeams() {
  mode.value           = 'teams'
  selectedIds.value    = []
  activePresetId.value = null
}

const poolValido = computed(() => selectedIds.value.length >= 5 && selectedIds.value.length <= 8)
function confirm() {
  if (poolValido.value) emit('conferma', selectedIds.value)
}

function clearFilters() {
  filterRarity.value = ''
  filterType.value   = ''
  page.value         = 0
}

// Azzera la pagina quando cambiano i filtri o l'ordinamento
watch([filterRarity, filterType, sortBy], () => { page.value = 0 })

// ── Stili helper ─────────────────────────────────────────────────────────────
function filterSelectStyle(active: boolean) {
  return {
    flex: 1, minWidth: '80px',
    background: 'var(--theme-input-bg)',
    border: `1.5px solid ${active ? 'var(--theme-accent)' : 'var(--theme-border-2)'}`,
    color: active ? 'var(--theme-accent)' : 'var(--theme-text-2)',
    borderRadius: '999px', padding: '8px 10px',
    fontFamily: "var(--ff-label, 'Saira Condensed', sans-serif)", fontSize: '14px', fontWeight: 600,
    outline: 'none', appearance: 'none' as const, WebkitAppearance: 'none' as const,
  }
}

function pageBtnStyle(disabled: boolean, active = false) {
  return {
    width: '32px', height: '32px', borderRadius: '8px',
    background: active ? 'var(--theme-tab-active)' : 'var(--theme-shimmer)',
    border: `1px solid ${active ? 'var(--theme-accent)' : 'var(--theme-border)'}`,
    color: disabled ? 'var(--theme-text-3)' : active ? 'var(--theme-accent)' : 'var(--theme-text-2)',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: "var(--ff-mono, 'JetBrains Mono', monospace)", fontSize: '12px', fontWeight: '700',
  }
}

// Indici visibili nella paginazione
const visiblePages = computed(() => {
  const start = Math.max(0, page.value - 2)
  const end   = Math.min(totalPages.value, page.value + 3)
  return Array.from({ length: end - start }, (_, i) => start + i)
})
</script>

<template>
  <!-- Overlay fisso a schermo intero -->
  <div :style="{
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 200,
    background: 'var(--theme-bg)', backdropFilter: 'blur(16px)',
    display: 'flex', flexDirection: 'column',
  }">

    <!-- Loading globale (standard app): copre tutto finché le immagini non sono pronte -->
    <div
      v-if="mode === 'manual' && ownedWaifu.length > 0 && !imagesReady"
      :style="{ position: 'absolute', inset: 0, zIndex: 50, background: 'var(--theme-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center' }"
    >
      <AppLoading />
    </div>

    <!-- Header ──────────────────────────────────────────────────────── -->
    <div :style="{ padding: '18px 18px 0', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexShrink: 0 }">
      <div>
        <div :style="{ fontFamily: FF.display, fontSize: '22px', color: 'var(--theme-text)', fontWeight: 900, lineHeight: 1.1 }">
          {{ mode === 'teams' ? 'Scegli il team' : 'Selezione manuale' }}
        </div>
        <div v-if="pixel?.name || (pixel?.x != null && pixel?.y != null)" :style="{ fontFamily: FF.mono, fontSize: '12px', color: 'var(--theme-text-3)', marginTop: '4px' }">
          {{ pixel?.name || `${pixel?.x}, ${pixel?.y}` }}
        </div>
      </div>
      <div :style="{ display: 'flex', gap: '8px', alignItems: 'center' }">
        <!-- Torna ai team (solo in manual se esistono team) -->
        <button
          v-if="mode === 'manual' && hasTeams"
          @click="setTeams"
          :style="{
            background: 'var(--theme-shimmer)', border: '1px solid var(--theme-border)',
            borderRadius: '999px', color: 'var(--theme-text-2)', fontFamily: FF.label,
            fontSize: '10px', letterSpacing: '0.15em', textTransform: 'uppercase',
            padding: '5px 12px', cursor: 'pointer',
          }"
        >← Team</button>
        <button @click="emit('chiudi')" :style="{ background: 'none', border: 'none', color: 'var(--theme-text-2)', cursor: 'pointer', display:'flex', alignItems:'center' }"><X :size="22" stroke-width="1.5" /></button>
      </div>
    </div>

    <!-- ── MODALITÀ TEAM ───────────────────────────────────────────── -->
    <template v-if="mode === 'teams'">
      <div :style="{ flex: 1, overflowY: 'auto', padding: '14px 18px 0' }">
        <div :style="{ fontFamily: FF.body, fontSize: '13px', color: 'var(--theme-text-2)', lineHeight: 1.4, marginBottom: '12px' }">
          💡 Scegli un team già salvato, oppure seleziona da 5 a 8 waifu per il tuo pool. Nella prossima schermata sceglierai la squadra di combattimento (da 1 a 8).
        </div>

        <!-- Lista preset team -->
        <div
          v-for="([id, preset]) in presets"
          :key="id"
          @click="selectPreset(id, (preset as any).waifu)"
          :style="{
            padding: '10px 14px', borderRadius: '14px', cursor: 'pointer',
            background: activePresetId === id ? 'var(--theme-tab-active)' : 'var(--theme-shimmer)',
            border: `1px solid ${activePresetId === id ? C.violet : 'rgba(174,156,255,0.15)'}`,
            transition: 'all 0.15s', marginBottom: '8px',
            display: 'flex', alignItems: 'center', gap: '10px',
          }"
        >
          <div :style="{ fontFamily: FF.label, fontSize: '11px', color: activePresetId === id ? C.violet : 'var(--theme-text)', textTransform: 'uppercase', minWidth: '70px', flexShrink: 0 }">
            {{ (preset as any).nome || 'Team' }}
          </div>
          <div :style="{ display: 'flex', gap: '4px', flex: 1 }">
            <!-- Miniature waifu del preset -->
            <template v-for="wid in ((preset as any).waifu || []).slice(0, 5)" :key="wid">
              <div
                :style="{
                  width: '28px', height: '28px', borderRadius: '6px', overflow: 'hidden',
                  border: `1px solid ${activePresetId === id ? C.violet + '60' : 'rgba(174,156,255,0.15)'}`,
                  background: '#12102a', flexShrink: 0,
                }"
              >
                <img
                  v-if="waifuCat?.find((w: any) => w.id === wid)?.asset_immagine || waifuCat?.find((w: any) => w.id === wid)?.asset_statica"
                  :src="waifuCat?.find((w: any) => w.id === wid)?.asset_immagine || waifuCat?.find((w: any) => w.id === wid)?.asset_statica"
                  :alt="waifuCat?.find((w: any) => w.id === wid)?.nome"
                  style="width:100%;height:100%;object-fit:cover;object-position:top"
                />
              </div>
            </template>
            <!-- Slot vuoti se meno di 5 -->
            <div
              v-for="i in Math.max(0, 5 - ((preset as any).waifu?.length ?? 0))"
              :key="`e${i}`"
              :style="{ width: '28px', height: '28px', borderRadius: '6px', background: 'rgba(255,255,255,0.04)', border: '1px dashed rgba(174,156,255,0.1)', flexShrink: 0 }"
            />
          </div>
          <span :style="{ color: activePresetId === id ? C.violet : 'rgba(174,156,255,0.3)', fontSize: '14px' }">
            {{ activePresetId === id ? '✓' : '›' }}
          </span>
        </div>

        <!-- Bottone selezione manuale -->
        <button
          @click="setManual"
          :style="{
            width: '100%', marginTop: '12px', padding: '13px',
            background: 'var(--theme-shimmer)', border: '1px solid var(--theme-border)',
            borderRadius: '999px', color: 'var(--theme-text-2)', fontFamily: FF.label,
            fontSize: '12px', letterSpacing: '0.2em', textTransform: 'uppercase', cursor: 'pointer',
          }"
        >MANUALE — scegli waifu</button>
      </div>

      <!-- CTA teams ─────────────────────────────────────────────────── -->
      <div :style="{ padding: '14px 16px 30px', flexShrink: 0 }">
        <button
          @click="confirm"
          :disabled="!poolValido"
          :style="{
            width: '100%', padding: '15px',
            background: poolValido ? 'linear-gradient(135deg, #c54a86, #ff85b6)' : 'var(--theme-shimmer)',
            border: 'none', borderRadius: '14px',
            cursor: poolValido ? 'pointer' : 'not-allowed',
            color: poolValido ? '#fff' : 'var(--theme-text-3)',
            fontFamily: FF.label, fontSize: '14px', letterSpacing: '0.2em',
            textTransform: 'uppercase', fontWeight: 700,
          }"
        ><Swords v-if="poolValido" :size="14" stroke-width="1.5" style="display:inline-block;vertical-align:middle;margin-right:6px;" />{{ poolValido ? 'Avvia Battaglia' : 'Seleziona un team' }}</button>
      </div>
    </template>

    <!-- ── MODALITÀ MANUALE ─────────────────────────────────────────── -->
    <template v-if="mode === 'manual'">
      <!-- Istruzione + contatore -->
      <div :style="{ padding: '10px 16px 0', flexShrink: 0, display:'flex', alignItems:'center', justifyContent:'space-between', gap:'8px' }">
        <div :style="{ fontFamily: FF.body, fontSize: '15px', color: 'var(--theme-text-2)', lineHeight: 1.4 }">
          Scegli da <strong :style="{ color: C.violet }">5 a 8 waifu</strong> per il tuo pool
        </div>
        <div :style="{ fontFamily: FF.mono, fontSize: '14px', fontWeight: 700, color: poolValido ? '#16a34a' : 'var(--theme-text-3)', flexShrink: 0 }">
          {{ selectedIds.length }}/8
        </div>
      </div>

      <!-- Filtri -->
      <div :style="{ padding: '8px 16px', display: 'flex', gap: '6px', flexShrink: 0 }">
        <select v-model="filterRarity" :style="filterSelectStyle(!!filterRarity)">
          <option value="">Tutte le rarità</option>
          <option v-for="r in RARITY_ORDER" :key="r" :value="r" :style="{ background: 'var(--theme-surface)', color: rarColors[r] }">{{ r.charAt(0).toUpperCase() + r.slice(1) }}</option>
        </select>
        <select v-model="filterType" :style="filterSelectStyle(!!filterType)">
          <option value="">Tutti i tipi</option>
          <option v-for="t in ['Arcana','Natura','Abisso','Ferro','Fuoco','Acqua']" :key="t" :value="t" :style="{ background: 'var(--theme-surface)' }">{{ t }}</option>
        </select>
        <select v-model="sortBy" :style="filterSelectStyle(sortBy !== 'rarita')">
          <option value="rarita">Rarità</option>
          <option value="velocita">Velocità</option>
          <option value="crit">% Critico</option>
        </select>
        <button v-if="filterRarity || filterType" @click="clearFilters" :style="{ background:'rgba(255,91,108,0.1)', border:'1px solid rgba(255,91,108,0.3)', borderRadius:'999px', color:C.err, fontFamily:FF.label, fontSize:'11px', padding:'4px 10px', cursor:'pointer', display:'flex', alignItems:'center', gap:'4px', flexShrink:0 }"><X :size="11" stroke-width="1.5" /></button>
      </div>

      <!-- Nessuna waifu -->
      <div v-if="ownedWaifu.length === 0" :style="{ padding: '32px 20px', textAlign: 'center' }">
        <Swords :size="32" stroke-width="1.5" style="margin-bottom:10px;opacity:0.6;" />
        <div :style="{ fontFamily: FF.label, fontSize: '13px', color: C.gold, letterSpacing: '0.15em', marginBottom: '8px' }">NESSUNA WAIFU DISPONIBILE</div>
        <div :style="{ fontFamily: FF.body, fontSize: '13px', color: 'var(--theme-text-2)', lineHeight: 1.6 }">
          Ogni waifu deve avere 4 mosse attacco assegnate.<br>
          Vai in <strong style="color:#9b59ff">Collezione → Mosse</strong>.
        </div>
      </div>

      <!-- Griglia waifu 2 colonne — card verticali (nome, immagine, mosse 2×2 sotto) -->
      <div :style="{ flex: 1, overflowY: 'auto', padding: '24px 16px 0' }">
        <div :style="{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px 12px' }">
          <div
            v-for="w in pageWaifu"
            :key="w.id"
            @click="toggle(w.id)"
            :style="{
              position: 'relative', cursor: 'pointer',
              display: 'flex', flexDirection: 'column', gap: '8px',
              padding: '8px',
              background: selectedIds.includes(w.id) ? (isDark ? 'rgba(255,200,97,0.12)' : 'rgba(154,111,0,0.08)') : cardBg,
              border: `2px solid ${selectedIds.includes(w.id) ? gold + 'cc' : cardBorder}`,
              borderRadius: '14px',
              boxShadow: selectedIds.includes(w.id) ? `0 4px 16px ${gold}40` : '0 4px 12px rgba(0,0,0,0.10)',
              transition: 'all 0.15s',
            }"
          >
            <!-- Nome -->
            <div :style="{ fontFamily:FF.display, fontSize:'15px', fontWeight:800, color:'var(--theme-text)', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }">
              {{ w.nome }}
            </div>
            <!-- Immagine -->
            <div :style="{ width:'100%', aspectRatio:'2/3', borderRadius:'10px', overflow:'hidden', background:'var(--theme-bg-secondary)', border:`2px solid ${rarColors[w.rarita] || 'var(--theme-border)'}` }">
              <img
                v-if="w.asset_immagine || w.asset_statica || w.asset_immersiva"
                :src="w.asset_immagine || w.asset_statica || w.asset_immersiva"
                :alt="w.nome"
                loading="eager" decoding="async"
                @load="markImgLoaded(w.id)"
                @error="markImgLoaded(w.id)"
                style="width:100%;height:100%;object-fit:cover;object-position:top;"
              />
              <div v-else style="width:100%;height:100%;display:grid;place-items:center;opacity:0.2;">
                <img src="~/assets/images/New_Logo.png" alt="" style="width:70%;" />
              </div>
            </div>

            <!-- Chip rarità — full-round, in alto a destra che sborda -->
            <div :style="{
                position: 'absolute', top: '-10px', right: '-10px',
                background: 'var(--theme-surface)',
                border: `1.5px solid ${w.rarita === 'leggendario' ? gold : rarColors[w.rarita] || '#aaa'}`,
                borderRadius: '999px', padding: '2px 10px',
                fontFamily: FF.label, fontSize: '11px', fontWeight: 800,
                color: w.rarita === 'leggendario' ? gold : rarColors[w.rarita] || '#aaa',
                textTransform: 'capitalize', zIndex: 3,
                boxShadow: '0 2px 8px rgba(0,0,0,0.2)',
              }">{{ w.rarita }}</div>

            <!-- Mosse 2×2 sotto l'immagine -->
            <div :style="{ minWidth:0, overflow:'hidden', display:'flex', flexDirection:'column', gap:'6px' }">

              <!-- Mosse 2×2 sotto l'immagine — piccole -->
              <div :style="{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'4px', overflow:'hidden' }">
                <div
                  v-for="(mossaId, slot) in (w._datiColl?.mosse_slot ?? {})"
                  :key="slot"
                  :style="{
                    background: getMossa(mossaId) ? moveTypeColor(getMossa(mossaId)!.tipologia) + (isDark ? '20' : '15') : cardBg,
                    border: `0.5px solid ${getMossa(mossaId) ? moveTypeColor(getMossa(mossaId)!.tipologia) + (isDark ? '66' : 'bb') : cardBorder}`,
                    borderRadius: '10px', padding: '4px 8px',
                    display: 'flex', flexDirection: 'column', gap: '0px', minWidth: 0, overflow: 'hidden',
                  }"
                >
                  <div :style="{ fontFamily:FF.label, fontSize:'11px', fontWeight:700, color: getMossa(mossaId) ? 'var(--theme-text)' : 'var(--theme-text-3)', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }">
                    {{ getMossa(mossaId)?.nome ?? '—' }}
                  </div>
                  <div v-if="getMossa(mossaId)?.tipologia" :style="{ fontFamily:FF.label, fontSize:'9px', fontWeight:600, color: moveTypeColor(getMossa(mossaId)!.tipologia) }">
                    {{ getMossa(mossaId)!.tipologia }}
                  </div>
                </div>
              </div>

              <!-- Stats veloci -->
              <div :style="{ display:'flex', gap:'10px' }">
                <span v-if="w.battleStats?.speed" :style="{ fontFamily:FF.mono, fontSize:'12px', fontWeight:600, color: isDark ? '#6cf0e0' : '#0891b2', display:'flex', alignItems:'center', gap:'3px' }">
                  <Zap :size="12" stroke-width="1.5" />{{ w.battleStats.speed }}
                </span>
                <span v-if="w.battleStats?.critChance" :style="{ fontFamily:FF.mono, fontSize:'12px', fontWeight:600, color: gold }">
                  💥 {{ w.battleStats.critChance }}%
                </span>
              </div>
            </div><!-- fine colonna destra -->

            <!-- Badge numero selezione — in basso a destra (evita sovrapposizione col chip rarità) -->
            <div
              v-if="selectedIds.includes(w.id)"
              :style="{
                position: 'absolute', bottom: '-12px', right: '-12px',
                width:'30px', height:'30px', borderRadius:'50%',
                background: gold, color: '#fff',
                display: 'grid', placeItems: 'center', fontWeight: 900, fontSize: '15px',
                boxShadow: `0 2px 10px ${gold}80`,
                border: '2px solid var(--theme-bg)',
                zIndex: 2,
              }"
            >{{ selectedIds.indexOf(w.id) + 1 }}</div>
          </div>
        </div>
      </div>

      <!-- Paginazione -->
      <div v-if="totalPages > 1" :style="{ display: 'flex', justifyContent: 'center', gap: '6px', padding: '8px 16px 0', flexShrink: 0 }">
        <button @click="page = Math.max(0, page - 1)" :disabled="page === 0" :style="pageBtnStyle(page === 0)">←</button>
        <button v-for="i in visiblePages" :key="i" @click="page = i" :style="pageBtnStyle(false, i === page)">{{ i + 1 }}</button>
        <button @click="page = Math.min(totalPages - 1, page + 1)" :disabled="page === totalPages - 1" :style="pageBtnStyle(page === totalPages - 1)">→</button>
      </div>

      <!-- CTA -->
      <div :style="{ padding: '10px 16px', flexShrink: 0 }">
        <button
          @click="confirm"
          :disabled="!poolValido"
          :style="{
            width: '100%', padding: '16px',
            background: poolValido ? 'linear-gradient(135deg, #c54a86, #ff85b6)' : 'var(--theme-shimmer)',
            border: 'none', borderRadius: '999px',
            cursor: poolValido ? 'pointer' : 'not-allowed',
            color: poolValido ? '#fff' : 'var(--theme-text-3)',
            fontFamily: FF.label, fontSize: '16px', letterSpacing: '0.18em',
            textTransform: 'uppercase', fontWeight: 800,
            boxShadow: poolValido ? '0 4px 24px rgba(197,74,134,0.5)' : 'none',
          }"
        ><Swords v-if="poolValido" :size="16" stroke-width="1.5" style="display:inline-block;vertical-align:middle;margin-right:6px;" />{{ poolValido ? 'Avanti →' : (selectedIds.length < 5 ? `Seleziona ancora ${5 - selectedIds.length}` : 'Max 8 waifu') }}</button>

        <div v-if="ownedWaifu.length > 0" :style="{ marginTop:'8px', padding:'8px 12px', background:'var(--theme-shimmer)', border:'1px solid var(--theme-border)', borderRadius:'10px', fontFamily:FF.body, fontSize:'12px', color:'var(--theme-text-3)', lineHeight:1.5, textAlign:'center' }">
          Le altre waifu non sono visibili perché non hai assegnato 4 mosse attacco. Vai in <strong style="color:#9b59ff">Collezione → Mosse</strong>.
        </div>
      </div>
    </template>

  </div>
</template>

// src/components/mappa/BattleModal.jsx
'use client';
import { useState, useMemo, useEffect } from 'react';
import { useScrollLock } from '@/lib/useScrollLock';
import { C, FF } from '@/app/gioco/_redesign/_shared';
import { CartaWaifu } from '@/components/CartaWaifu';
import { RARITA } from '@/lib/constants';

const PAGE_SIZE = 9; // 9 per pagina (3×3 griglia)

// Filtri disponibili
const RARITY_ORDER = ['comune', 'raro', 'epico', 'leggendario', 'immersivo'];

function PresetCard({ preset, waifuCat, isActive, onSelect }) {
  const w5 = (preset.waifu || []).map(id => waifuCat?.find(w => w.id === id)).filter(Boolean);
  return (
    <div onClick={onSelect} style={{
      padding: '10px 14px', borderRadius: 14, cursor: 'pointer',
      background: isActive ? 'rgba(167,139,250,0.18)' : 'rgba(255,255,255,0.04)',
      border: `1px solid ${isActive ? C.violet : 'rgba(174,156,255,0.15)'}`,
      transition: 'all 0.15s', marginBottom: 8,
      display: 'flex', alignItems: 'center', gap: 10,
    }}>
      <div style={{ fontFamily: FF.label, fontSize: 11, color: isActive ? C.violet : 'rgba(241,235,255,0.8)', textTransform: 'uppercase', minWidth: 70, flexShrink: 0 }}>
        {preset.nome || 'Team'}
      </div>
      <div style={{ display: 'flex', gap: 4, flex: 1 }}>
        {w5.map((w, i) => (
          <div key={i} style={{ width: 28, height: 28, borderRadius: 6, overflow: 'hidden', border: `1px solid ${isActive ? C.violet + '60' : 'rgba(174,156,255,0.15)'}`, background: '#12102a', flexShrink: 0 }}>
            {(w.asset_immagine || w.asset_statica) && (
              <img src={w.asset_immagine || w.asset_statica} alt={w.nome} style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top' }} />
            )}
          </div>
        ))}
        {Array.from({ length: Math.max(0, 5 - w5.length) }).map((_, i) => (
          <div key={`e${i}`} style={{ width: 28, height: 28, borderRadius: 6, background: 'rgba(255,255,255,0.04)', border: '1px dashed rgba(174,156,255,0.1)', flexShrink: 0 }} />
        ))}
      </div>
      <span style={{ color: isActive ? C.violet : 'rgba(174,156,255,0.3)', fontSize: 14 }}>{isActive ? '✓' : '›'}</span>
    </div>
  );
}

export default function BattleModal({ pixel, collezione, waifuCat, onConfirm, onClose }) {
  useScrollLock();
  const teams = collezione?.teams || {};
  const presets = Object.entries(teams).filter(([, t]) => t.waifu?.length === 5);
  const hasTeams = presets.length > 0;

  // Offset top per non andare sotto l'header
  const [topOffset, setTopOffset] = useState(0);
  useEffect(() => {
    const hdr = document.querySelector('.hdr-root');
    const ntabs = document.querySelector('.ntabs-root');
    setTopOffset((hdr ? hdr.getBoundingClientRect().height : 0) + (ntabs ? ntabs.getBoundingClientRect().height : 0));
  }, []);

  // mode: 'teams' (default se ho team) | 'manual'
  const [mode, setMode] = useState(hasTeams ? 'teams' : 'manual');
  const [selectedIds, setSelectedIds] = useState([]);
  const [activePresetId, setActivePresetId] = useState(null);

  // Paginazione e filtri (solo in modalità manual)
  const [page, setPage] = useState(0);
  const [filterRarity, setFilterRarity] = useState('');
  const [filterType, setFilterType] = useState('');
  const [sortBy, setSortBy] = useState('rarita'); // rarita | velocita | crit

  const ownedWaifu = useMemo(() => {
    const list = Object.entries(collezione?.waifu || {})
      .map(([id, dati]) => {
        const w = waifuCat?.find(x => x.id === id);
        if (!w) return null;
        // Solo waifu con 4 mosse assegnate sono selezionabili per la battaglia
        const mosseAssegnate = Object.values(dati.mosse_slot ?? {}).filter(Boolean).length;
        if (mosseAssegnate < 4) return null;
        return { ...w, ...dati, _datiColl: dati };
      })
      .filter(Boolean);
    // Ordina in base al criterio scelto
    if (sortBy === 'rarita') list.sort((a, b) => RARITY_ORDER.indexOf(b.rarita) - RARITY_ORDER.indexOf(a.rarita));
    else if (sortBy === 'velocita') list.sort((a, b) => (b.battleStats?.speed ?? 0) - (a.battleStats?.speed ?? 0));
    else if (sortBy === 'crit') list.sort((a, b) => (b.battleStats?.critChance ?? 0) - (a.battleStats?.critChance ?? 0));
    return list;
  }, [collezione, waifuCat, sortBy]);

  const filtered = useMemo(() => ownedWaifu.filter(w => {
    // Fix: confronto case-insensitive per rarità e tipo
    if (filterRarity && (w.rarita?.toLowerCase() !== filterRarity.toLowerCase())) return false;
    if (filterType && (w.tipo !== filterType && w.battleStats?.type !== filterType)) return false;
    return true;
  }), [ownedWaifu, filterRarity, filterType]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const pageWaifu  = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const toggle = (id) => {
    setActivePresetId(null);
    setSelectedIds(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : prev.length < 5 ? [...prev, id] : prev
    );
  };

  const selectPreset = (id, presetWaifu) => {
    const valid = presetWaifu.filter(wid => ownedWaifu.some(w => w.id === wid));
    if (valid.length === 5) { setSelectedIds(valid); setActivePresetId(id); }
  };

  const confirm = () => {
    if (selectedIds.length === 5) onConfirm(selectedIds);
  };

  const rarColors = {
    comune: '#b4bcc8', raro: '#5aa9ff', epico: '#b573ff',
    leggendario: '#ffc861', immersivo: '#ff7eb6',
  };

  return (
    <div style={{
      position: 'fixed', top: topOffset, left: 0, right: 0, bottom: 0, zIndex: 200,
      background: 'rgba(3,2,12,0.96)', backdropFilter: 'blur(16px)',
      display: 'flex', flexDirection: 'column',
    }}>
      {/* Header */}
      <div style={{ padding: '18px 18px 0', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexShrink: 0 }}>
        <div>
          <div style={{ fontFamily: FF.label, fontSize: 9, letterSpacing: '0.22em', color: C.sakura, textTransform: 'uppercase' }}>◆ CONQUISTA</div>
          <div style={{ fontFamily: FF.display, fontSize: 17, color: '#fff', fontWeight: 800 }}>
            {mode === 'teams' ? 'Scegli il team' : 'Selezione manuale'}
          </div>
          <div style={{ fontFamily: FF.mono, fontSize: 10, color: 'rgba(241,235,255,0.4)', marginTop: 2 }}>
            {pixel?.name || `(${pixel?.x}, ${pixel?.y})`} {mode === 'manual' && `· ${selectedIds.length}/5`}
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {mode === 'manual' && hasTeams && (
            <button onClick={() => { setMode('teams'); setSelectedIds([]); setActivePresetId(null); }} style={{
              background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(174,156,255,0.2)',
              borderRadius: 8, color: 'rgba(241,235,255,0.6)', fontFamily: FF.label,
              fontSize: 10, letterSpacing: '0.15em', textTransform: 'uppercase', padding: '5px 10px', cursor: 'pointer',
            }}>← Team</button>
          )}
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'rgba(241,235,255,0.4)', fontSize: 22, cursor: 'pointer' }}>✕</button>
        </div>
      </div>

      {/* ── MODALITÀ TEAM ─────────────────────────────────────────── */}
      {mode === 'teams' && (
        <>
          <div style={{ flex: 1, overflowY: 'auto', padding: '14px 18px 0' }}>
            <div style={{ fontFamily: FF.body, fontSize: 11, color: 'rgba(241,235,255,0.5)', lineHeight: 1.4, marginBottom: 12 }}>
              💡 Scegli un team già salvato, oppure seleziona 5 waifu con cui vuoi combattere. Nella prossima schermata potrai scegliere le 3 migliori waifu per affrontare il primo round.
            </div>
            {presets.map(([id, preset]) => (
              <PresetCard
                key={id} preset={preset} waifuCat={waifuCat}
                isActive={activePresetId === id}
                onSelect={() => selectPreset(id, preset.waifu)}
              />
            ))}

            {/* Bottone selezione manuale */}
            <button
              onClick={() => { setMode('manual'); setSelectedIds([]); setActivePresetId(null); }}
              style={{
                width: '100%', marginTop: 12, padding: '13px',
                background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(174,156,255,0.2)',
                borderRadius: 14, color: 'rgba(241,235,255,0.6)', fontFamily: FF.label,
                fontSize: 12, letterSpacing: '0.2em', textTransform: 'uppercase', cursor: 'pointer',
              }}
            >MANUALE — scegli waifu</button>
          </div>
          <div style={{ padding: '14px 16px 30px', flexShrink: 0 }}>
            <button
              onClick={confirm}
              disabled={selectedIds.length !== 5}
              style={{
                width: '100%', padding: '15px',
                background: selectedIds.length === 5 ? 'linear-gradient(135deg, #c54a86, #ff85b6)' : 'rgba(255,255,255,0.06)',
                border: 'none', borderRadius: 14,
                cursor: selectedIds.length === 5 ? 'pointer' : 'not-allowed',
                color: selectedIds.length === 5 ? '#fff' : 'rgba(241,235,255,0.3)',
                fontFamily: FF.label, fontSize: 14, letterSpacing: '0.2em',
                textTransform: 'uppercase', fontWeight: 700,
              }}
            >{selectedIds.length === 5 ? '⚔ Avvia Battaglia' : 'Seleziona un team'}</button>
          </div>
        </>
      )}

      {/* ── MODALITÀ MANUALE ──────────────────────────────────────── */}
      {mode === 'manual' && (
        <>
          {/* Istruzione per l'utente */}
          <div style={{ padding: '8px 16px 0', flexShrink: 0 }}>
            <div style={{ fontFamily: FF.body, fontSize: 11, color: 'rgba(241,235,255,0.5)', lineHeight: 1.4, marginBottom: 6 }}>
              💡 Seleziona <strong style={{ color: C.gold }}>5 waifu</strong> con cui vuoi combattere. Nella prossima schermata potrai scegliere le 3 migliori waifu per affrontare il primo round.
            </div>
          </div>

          {/* Filtri e ordinamento */}
          <div style={{ padding: '6px 16px 0', display: 'flex', gap: 5, flexShrink: 0, flexWrap: 'wrap' }}>
            <select value={filterRarity} onChange={e => { setFilterRarity(e.target.value); setPage(0); }}
              style={filterSelectStyle(!!filterRarity)}>
              <option value="">Rarità</option>
              {RARITY_ORDER.map(r => <option key={r} value={r} style={{ background: '#0d0a26', color: rarColors[r] }}>{r}</option>)}
            </select>
            <select value={filterType} onChange={e => { setFilterType(e.target.value); setPage(0); }}
              style={filterSelectStyle(!!filterType)}>
              <option value="">Tipo</option>
              {['Arcana','Natura','Abisso','Ferro','Fuoco'].map(t => <option key={t} value={t} style={{ background: '#0d0a26' }}>{t}</option>)}
            </select>
            <select value={sortBy} onChange={e => { setSortBy(e.target.value); setPage(0); }}
              style={filterSelectStyle(sortBy !== 'rarita')}>
              <option value="rarita">↕ Rarità</option>
              <option value="velocita">↕ Velocità</option>
              <option value="crit">↕ % Critico</option>
            </select>
          </div>
          {(filterRarity || filterType) && (
            <div style={{ padding: '3px 16px 0', flexShrink: 0 }}>
              <button onClick={() => { setFilterRarity(''); setFilterType(''); setPage(0); }} style={{
                background: 'rgba(255,91,108,0.08)', border: '1px solid rgba(255,91,108,0.25)',
                borderRadius: 8, color: C.err, fontFamily: FF.label, fontSize: 10,
                letterSpacing: '0.15em', textTransform: 'uppercase', padding: '4px 12px', cursor: 'pointer',
              }}>Cancella filtri</button>
            </div>
          )}
          <div style={{ padding: '3px 16px', fontFamily: FF.mono, fontSize: 10, color: 'rgba(241,235,255,0.3)', flexShrink: 0 }}>
            {filtered.length} waifu · pagina {page + 1}/{Math.max(1, totalPages)} · {selectedIds.length}/5 selezionate
          </div>

          {/* Griglia paginata: 3 colonne */}
          {ownedWaifu.length === 0 && (
            <div style={{ padding: '24px 16px', textAlign: 'center' }}>
              <div style={{ fontSize: 26, marginBottom: 8 }}>⚔</div>
              <div style={{ fontFamily: FF.label, fontSize: 10, color: C.gold, letterSpacing: '0.15em', marginBottom: 8 }}>NESSUNA WAIFU DISPONIBILE</div>
              <div style={{ fontFamily: FF.body, fontSize: 11, color: 'rgba(241,235,255,0.5)', lineHeight: 1.6 }}>
                Per combattere ogni waifu deve avere 4 mosse attacco assegnate.<br/>
                Vai in <strong style={{color:'#9b59ff'}}>Collezione → Mosse</strong> per assegnare le mosse.
              </div>
            </div>
          )}
          <div style={{ flex: 1, overflowY: 'auto', overflowX: 'hidden', padding: '4px 8px 0' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 4 }}>
              {pageWaifu.map(w => {
                const selIdx = selectedIds.indexOf(w.id);
                const sel = selIdx !== -1;
                return (
                  <div
                    key={w.id}
                    onClick={() => toggle(w.id)}
                    style={{
                      position: 'relative', cursor: 'pointer',
                      // Riduzione uniforme con overflow nascosto per evitare scroll orizzontale
                      transform: 'scale(0.78)', transformOrigin: 'top left',
                      width: '128%', // compensa il transform per il layout
                    }}
                  >
                    <div style={{
                      outline: sel ? `3px solid ${C.gold}` : '3px solid transparent',
                      borderRadius: 14, boxShadow: sel ? `0 0 14px ${C.gold}50` : 'none',
                      transition: 'outline 0.15s',
                    }}>
                      <CartaWaifu waifu={w} datiCollezione={w._datiColl} dimensione="piccola" evidenziato={false} />
                    </div>
                    {sel && (
                      <div style={{
                        position: 'absolute', top: 5, right: -3, zIndex: 2,
                        width: 22, height: 22, borderRadius: '50%',
                        background: C.gold, color: '#1a0024',
                        display: 'grid', placeItems: 'center', fontWeight: 900, fontSize: 12,
                        boxShadow: `0 2px 8px ${C.gold}80`,
                      }}>{selIdx + 1}</div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Paginazione */}
          {totalPages > 1 && (
            <div style={{ display: 'flex', justifyContent: 'center', gap: 8, padding: '8px 16px 0', flexShrink: 0 }}>
              <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0} style={pageBtn(page === 0)}>←</button>
              {Array.from({ length: totalPages }, (_, i) => (
                <button key={i} onClick={() => setPage(i)} style={pageBtn(false, i === page)}>
                  {i + 1}
                </button>
              )).slice(Math.max(0, page - 2), Math.min(totalPages, page + 3))}
              <button onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))} disabled={page === totalPages - 1} style={pageBtn(page === totalPages - 1)}>→</button>
            </div>
          )}

          {/* Bottone conferma */}
          <div style={{ padding: '10px 16px 28px', flexShrink: 0 }}>
            <button
              onClick={confirm}
              disabled={selectedIds.length !== 5}
              style={{
                width: '100%', padding: '14px',
                background: selectedIds.length === 5 ? 'linear-gradient(135deg, #c54a86, #ff85b6)' : 'rgba(255,255,255,0.06)',
                border: 'none', borderRadius: 14,
                cursor: selectedIds.length === 5 ? 'pointer' : 'not-allowed',
                color: selectedIds.length === 5 ? '#fff' : 'rgba(241,235,255,0.3)',
                fontFamily: FF.label, fontSize: 14, letterSpacing: '0.2em',
                textTransform: 'uppercase', fontWeight: 700,
              }}
            >{selectedIds.length === 5 ? '⚔ Avvia Battaglia' : `Seleziona ancora ${5 - selectedIds.length}`}</button>
            {ownedWaifu.length > 0 && (
              <div style={{ marginTop: 8, padding: '8px 12px', background: 'rgba(155,89,255,0.06)', border: '1px solid rgba(155,89,255,0.2)', borderRadius: 10, fontFamily: FF.body, fontSize: 11, color: 'rgba(241,235,255,0.45)', lineHeight: 1.5, textAlign: 'center' }}>
                Le altre waifu non sono visibili perché non hai ancora assegnato le 4 mosse attacco. Assegnale dalla sezione <strong style={{color:'#9b59ff'}}>Collezione → Mosse</strong>.
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}

function filterSelectStyle(active = false) {
  return {
    flex: 1, minWidth: 90, background: 'rgba(255,255,255,0.06)',
    border: `1px solid ${active ? 'rgba(174,156,255,0.4)' : 'rgba(174,156,255,0.2)'}`,
    color: active ? '#fff' : 'rgba(241,235,255,0.5)',
    borderRadius: 8, padding: '5px 6px',
    fontFamily: "'DM Sans', sans-serif", fontSize: 11,
  };
}

function pageBtn(disabled, active = false) {
  return {
    width: 32, height: 32, borderRadius: 8,
    background: active ? 'rgba(167,139,250,0.2)' : 'rgba(255,255,255,0.04)',
    border: `1px solid ${active ? 'rgba(167,139,250,0.4)' : 'rgba(174,156,255,0.15)'}`,
    color: disabled ? 'rgba(241,235,255,0.2)' : active ? '#a78bfa' : 'rgba(241,235,255,0.6)',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: "'JetBrains Mono', monospace", fontSize: 12, fontWeight: 700,
  };
}
