// pages/onboarding.vue
<!-- ============================================================
  Pagina di onboarding: creazione del primo profilo utente.
  Assegna nome impero, colore bandiera e pacchetti benvenuto.
  Equivalente di src/app/onboarding/page.jsx nel Next.js originale.
  ============================================================ -->
<script setup lang="ts">
import { useAuthStore }         from '~/stores/auth'
import { getUserProfile, createUserProfile, setCollezione } from '~/utils/firestoreService'

definePageMeta({ middleware: 'auth' })

const authStore    = useAuthStore()
const router       = useRouter()
const nomeImpero   = ref('')
const coloreImpero = ref('#f59e0b')
const busy         = ref(false)

const COLORI = ['#f59e0b', '#ec4899', '#a855f7', '#06d6a0', '#3b82f6', '#ef4444', '#10b981', '#fbbf24']

// Se l'utente ha già un profilo, va direttamente al gioco
onMounted(async () => {
  if (!authStore.user) return
  const profilo = await getUserProfile(authStore.user.uid)
  if (profilo) router.replace('/gioco')
})

async function conferma() {
  if (!nomeImpero.value.trim() || !authStore.user) return
  busy.value = true
  try {
    const uid = authStore.user.uid

    await createUserProfile(uid, {
      nomeImpero:             nomeImpero.value.trim(),
      coloreImpero:           coloreImpero.value,
      email:                  authStore.user.email,
      displayName:            authStore.user.displayName || nomeImpero.value.trim(),
      energia:                10,
      pacchettiOmaggio:       2,
      pacchettiBenvenuto:     5,
      pacchettiSfida:         0,
      ultimaRicaricaEnergia:  new Date(),
      ultimaRicaricaPacchetti: new Date(),
    })

    await setCollezione(uid, { waifu: {}, outfit: {}, pose: {}, equipaggiamento: {}, preset: {} })

    router.replace('/gioco')
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center p-4">
    <div class="fade-up w-full max-w-[460px] rounded-2xl p-7"
         style="background:rgba(15,10,30,0.7);backdrop-filter:blur(12px);
                border:1px solid rgba(245,158,11,0.3);
                box-shadow:0 0 40px rgba(168,85,247,0.2)">

      <!-- Header -->
      <div class="text-center mb-5">
        <img src="~/assets/images/Logo.png" alt="Impero delle Waifu" class="w-32 h-auto mx-auto" style="mask-image: radial-gradient(ellipse 90% 85% at 50% 50%, black 68%, transparent 92%); -webkit-mask-image: radial-gradient(ellipse 90% 85% at 50% 50%, black 68%, transparent 92%);" />
        <h2 class="font-cinzel tracking-widest text-xl mt-2 mb-0
                   bg-gradient-to-br from-amber-400 via-pink-500 to-purple-500
                   bg-clip-text text-transparent">
          FONDA IL TUO IMPERO
        </h2>
        <p class="text-sm leading-relaxed mt-3" style="color:#d4c5b9">
          Benvenuta/o nell'Impero delle Waifu. Inizia scegliendo il nome del tuo dominio
          e riceverai
          <strong class="text-amber-400">5 pacchetti di benvenuto</strong> senza doppioni.
        </p>
      </div>

      <!-- Nome -->
      <label class="text-xs tracking-widest font-cinzel text-purple-400">
        NOME IMPERO
      </label>
      <input
        v-model="nomeImpero"
        maxlength="30"
        placeholder="Es. Impero del Sol Levante"
        class="w-full px-3 py-3 mt-1.5 mb-4 rounded-lg text-sm text-amber-50
               placeholder-amber-50/30 outline-none box-border
               focus:border-amber-400/60 transition-colors"
        style="background:rgba(0,0,0,0.4);border:1px solid rgba(245,158,11,0.3)"
      />

      <!-- Colore bandiera -->
      <label class="text-xs tracking-widest font-cinzel text-purple-400 block">
        COLORE BANDIERA
      </label>
      <div class="flex gap-1.5 mt-2 flex-wrap">
        <button
          v-for="c in COLORI"
          :key="c"
          class="w-8 h-8 rounded-full cursor-pointer transition-transform hover:scale-110"
          :style="{
            background:  c,
            border:      coloreImpero === c ? '3px solid #fff' : '2px solid rgba(255,255,255,0.2)',
            boxShadow:  `0 0 12px ${c}80`,
          }"
          @click="coloreImpero = c"
        />
      </div>

      <!-- CTA -->
      <button
        :disabled="!nomeImpero.trim() || busy"
        class="w-full py-3 mt-5 rounded-lg font-cinzel font-semibold text-sm
               tracking-widest text-black cursor-pointer
               bg-gradient-to-r from-amber-400 to-pink-500
               hover:opacity-90 transition-opacity disabled:opacity-40"
        @click="conferma"
      >
        {{ busy ? 'CREAZIONE...' : "FONDA L'IMPERO" }}
      </button>
    </div>
  </div>
</template>

// src/app/onboarding/page.jsx
// src/app/onboarding/page.jsx
'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/AuthContext';
import { createUserProfile, getUserProfile, setCollezione } from '@/lib/firestoreService';

export default function OnboardingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const [nomeImpero, setNomeImpero] = useState('');
  const [coloreImpero, setColoreImpero] = useState('#f59e0b');
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (loading) return;
    if (!user) { router.replace('/login'); return; }
    (async () => {
      const p = await getUserProfile(user.uid);
      if (p) router.replace('/gioco');
    })();
  }, [user, loading]);

  const conferma = async () => {
    if (!nomeImpero.trim()) return;
    setBusy(true);
    try {
      // 1) Profilo utente
      await createUserProfile(user.uid, {
        nomeImpero: nomeImpero.trim(),
        coloreImpero,
        email: user.email,
        displayName: user.displayName || nomeImpero.trim(),
        energia: 10,
        pacchettiOmaggio: 2, // 2 pacchetti omaggio (ricarica ogni 12h)
        pacchettiBenvenuto: 5, // 5 pacchetti benvenuto (solo una volta)
        pacchettiSfida: 0, // Pacchetti vinti dalle battaglie
        ultimaRicaricaEnergia: new Date(),
        ultimaRicaricaPacchetti: new Date(),
      });

      // 2) Collezione vuota iniziale
      await setCollezione(user.uid, { waifu: {}, outfit: {}, pose: {}, equipaggiamento: {}, preset: {} });

      // 3) Vai al gioco - i pacchetti si aprono nella sezione Sbusta
      router.replace('/gioco');
    } finally { setBusy(false); }
  };

  if (loading || !user) return null;

  return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16 }}>
      <div className="fade-up" style={card}>
        <div style={{ textAlign: 'center', marginBottom: 20 }}>
          <div className="glow-pulse" style={{ fontSize: 50, color: '#f59e0b' }}>♛</div>
          <h2 style={titolo}>FONDA IL TUO IMPERO</h2>
          <p style={{ color: '#d4c5b9', fontSize: 13, lineHeight: 1.6, marginTop: 12 }}>
            Benvenuta/o nell'Impero delle Waifu. Inizia scegliendo il nome del tuo dominio
            e riceverai <strong style={{ color: '#f59e0b' }}>5 pacchetti di benvenuto</strong> senza doppioni.
          </p>
        </div>
          <label style={{ fontSize: 11, letterSpacing: 2, color: '#a855f7', fontFamily: 'Cinzel, serif' }}>
            NOME IMPERO
          </label>
          <input value={nomeImpero} onChange={e => setNomeImpero(e.target.value)} maxLength={30}
                 placeholder="Es. Impero del Sol Levante" style={inputStyle} />
          <label style={{ fontSize: 11, letterSpacing: 2, color: '#a855f7', fontFamily: 'Cinzel, serif', marginTop: 8, display: 'block' }}>
            COLORE BANDIERA
          </label>
          <div style={{ display: 'flex', gap: 6, marginTop: 8, flexWrap: 'wrap' }}>
            {['#f59e0b', '#ec4899', '#a855f7', '#06d6a0', '#3b82f6', '#ef4444', '#10b981', '#fbbf24'].map(c => (
              <button key={c} onClick={() => setColoreImpero(c)}
                style={{
                  width: 32, height: 32, borderRadius: '50%',
                  background: c, border: coloreImpero === c ? '3px solid #fff' : '2px solid rgba(255,255,255,0.2)',
                  cursor: 'pointer', boxShadow: `0 0 12px ${c}80`,
                }} />
            ))}
          </div>
          <button onClick={conferma} disabled={!nomeImpero.trim() || busy} style={{ ...btnPrimario, marginTop: 20, opacity: !nomeImpero.trim() ? 0.4 : 1 }}>
            {busy ? 'CREAZIONE...' : 'FONDA L\'IMPERO'}
          </button>
        </div>
      </div>
  );
}

const card = {
  width: '100%', maxWidth: 460,
  background: 'rgba(15,10,30,0.7)', backdropFilter: 'blur(12px)',
  border: '1px solid rgba(245,158,11,0.3)',
  borderRadius: 16, padding: 28,
  boxShadow: '0 0 40px rgba(168,85,247,0.2)',
};

const titolo = {
  fontFamily: 'Cinzel, serif', letterSpacing: 4,
  background: 'linear-gradient(135deg, #f59e0b, #ec4899, #a855f7)',
  WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
  fontSize: 22, margin: '8px 0 0',
};

const inputStyle = {
  width: '100%', padding: 12, marginTop: 6,
  background: 'rgba(0,0,0,0.4)',
  border: '1px solid rgba(245,158,11,0.3)',
  borderRadius: 8, color: '#f5e6d3', fontFamily: 'inherit', fontSize: 14,
  boxSizing: 'border-box',
};

const btnPrimario = {
  width: '100%', padding: 12,
  background: 'linear-gradient(135deg, #f59e0b, #ec4899)',
  border: 'none', color: '#000', fontWeight: 600,
  fontFamily: 'Cinzel, serif', fontSize: 13, letterSpacing: 3,
  borderRadius: 8, cursor: 'pointer',
};
