// components/NegozioOverlay.vue
<!-- ============================================================
  Overlay Negozio — funzionale.
  · Beni con Kisses: pack sfida (x1 / x10), energia, Hard Pass, Trade Pass
    → endpoint /api/kisses/buy-*
  · Ricarica Kisses con denaro reale via PayPal (tagli xs/sm/md/lg)
    → /api/paypal/create-order-kisses + capture-order-kisses
  Prezzi da /api/negozio/config (Firestore config/prezzi + default).
  ============================================================ -->
<script setup lang="ts">
import { useAuthStore } from '~/stores/auth'
import { Gift, Package, Zap, Flame, Repeat } from 'lucide-vue-next'
import type { ProfiloUtente } from '~/types/game'

const props = defineProps<{ profilo: ProfiloUtente | null }>()
const emit = defineEmits<{
  kissesUpdate:  [kisses: number]
  profileUpdate: [patch: Record<string, unknown>]
  close:         []
}>()

const authStore = useAuthStore()
const config    = useRuntimeConfig()
const { t }     = useI18n()

const C = {
  gold: '#f5c560', sakura: '#ff85b6', ok: '#58e0a3', err: '#ff5b6c',
}
const FF = {
  display: "var(--ff-display, 'Fredoka', sans-serif)",
  label:   "var(--ff-label, 'Saira Condensed', sans-serif)",
  body:    "var(--ff-body, 'DM Sans', sans-serif)",
}

// Kisses locali: partono dal profilo, si aggiornano dopo ogni acquisto
const kisses = ref<number>(Number(props.profilo?.kisses ?? 0))
watch(() => props.profilo?.kisses, (k) => { if (typeof k === 'number') kisses.value = k })

const hasHardPass  = computed(() => !!(props.profilo as any)?.hardPass)
const hasTradePass = computed(() => !!(props.profilo as any)?.tradePass || !!props.profilo?.tradePassActive)

interface Taglio { id: string; kisses: number; bonus?: number; price_eur: string; label?: string }
const beni  = ref<Record<string, { kisses: number }>>({})
const tagli = ref<Taglio[]>([])
const caricato = ref(false)
const busy     = ref<string | null>(null)
const notif    = ref<{ testo: string; colore: string } | null>(null)

function flash(testo: string, colore = C.ok) {
  notif.value = { testo, colore }
  setTimeout(() => { notif.value = null }, 2600)
}

// ── Catalogo beni (metadati UI) ──────────────────────────────
const BENI_META: Record<string, { icon: unknown; color: string; titleKey: string; descKey: string }> = {
  pack_sfida:    { icon: Gift,    color: '#ff85b6', titleKey: 'shop.item_challenge_pack',    descKey: 'shop.item_challenge_pack_desc' },
  pack_sfida_10: { icon: Package, color: '#a78bfa', titleKey: 'shop.item_challenge_pack_10', descKey: 'shop.item_challenge_pack_10_desc' },
  energia:       { icon: Zap,     color: '#f5c560', titleKey: 'shop.item_energy',            descKey: 'shop.item_energy_desc' },
  pass_hard:     { icon: Flame,   color: '#ff5b6c', titleKey: 'shop.item_hard_pass',         descKey: 'shop.item_hard_pass_desc' },
  trade_pass:    { icon: Repeat,  color: '#6cf0e0', titleKey: 'shop.item_trade_pass',        descKey: 'shop.item_trade_pass_desc' },
}
const beniOrder = ['pack_sfida', 'pack_sfida_10', 'energia', 'pass_hard', 'trade_pass']
const beniList = computed(() =>
  beniOrder
    .filter(id => beni.value[id])
    .map(id => ({ id, kisses: beni.value[id].kisses, ...BENI_META[id] }))
    // Pass già posseduti: nascosti
    .filter(b => !(b.id === 'pass_hard' && hasHardPass.value) && !(b.id === 'trade_pass' && hasTradePass.value)),
)

onMounted(async () => {
  try {
    const data = await ($fetch('/api/negozio/config')) as { prezzi: { beni: Record<string, { kisses: number }>; tagli_kisses: Taglio[] } }
    beni.value  = data.prezzi.beni
    tagli.value = data.prezzi.tagli_kisses
  } catch {
    beni.value = {
      pack_sfida: { kisses: 50 }, pack_sfida_10: { kisses: 450 }, energia: { kisses: 20 },
      pass_hard: { kisses: 500 }, trade_pass: { kisses: 100 },
    }
    tagli.value = [
      { id: 'xs', kisses: 100, bonus: 0, price_eur: '0.99' },
      { id: 'sm', kisses: 300, bonus: 30, price_eur: '2.49' },
      { id: 'md', kisses: 600, bonus: 80, price_eur: '3.99' },
      { id: 'lg', kisses: 1400, bonus: 200, price_eur: '7.99' },
    ]
  } finally {
    caricato.value = true
    loadPayPal()
  }
})

// ── Acquisto con Kisses ──────────────────────────────────────
const BENE_ENDPOINT: Record<string, string> = {
  pack_sfida:    '/api/kisses/buy-pack',
  pack_sfida_10: '/api/kisses/buy-pack-10',
  energia:       '/api/kisses/buy-energia',
  pass_hard:     '/api/kisses/buy-passhard',
  trade_pass:    '/api/kisses/buy-tradepass',
}
async function acquistaBene(id: string) {
  if (busy.value) return
  const costo = beni.value[id]?.kisses ?? 0
  if (kisses.value < costo) { flash(t('shop.missing_kisses', { n: costo - kisses.value }), C.err); return }
  const endpoint = BENE_ENDPOINT[id]
  if (!endpoint) return
  busy.value = id
  try {
    const token = await authStore.user?.getIdToken()
    const data = await ($fetch(endpoint, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
    })) as { kissesCost: number; pacchettiAggiunti?: number }
    kisses.value -= data.kissesCost
    emit('kissesUpdate', kisses.value)
    // Riflette localmente l'effetto del bene sul profilo
    const patch: Record<string, unknown> = { kisses: kisses.value }
    if (id === 'pack_sfida')    patch.pacchettiSfida = ((props.profilo as any)?.pacchettiSfida ?? 0) + 1
    if (id === 'pack_sfida_10') patch.pacchettiSfida = ((props.profilo as any)?.pacchettiSfida ?? 0) + (data.pacchettiAggiunti ?? 10)
    if (id === 'energia')       patch.energia = Math.min(100, (props.profilo?.energia ?? 0) + 10)
    if (id === 'pass_hard')     patch.hardPass = true
    if (id === 'trade_pass')    patch.tradePass = true
    emit('profileUpdate', patch)
    flash('✓ ' + t(BENI_META[id].titleKey))
  } catch (e: any) {
    flash(e?.data?.message ?? t('shop.purchase_error'), C.err)
  } finally {
    busy.value = null
  }
}

// ── Ricarica Kisses con PayPal ───────────────────────────────
const selTaglio    = ref<string>('sm')
const ppRef        = ref<HTMLElement | null>(null)
const ppRendered   = ref(false)
const ppState      = ref<'idle' | 'loading' | 'error'>('idle')
const ppErr        = ref('')
const taglioScelto = computed(() => tagli.value.find(t => t.id === selTaglio.value) ?? tagli.value[0])

function renderPayPal() {
  const paypal = (window as any).paypal
  if (!ppRef.value || !paypal || ppRendered.value) return
  ppRendered.value = true
  ppRef.value.innerHTML = ''
  paypal.Buttons({
    style: { layout: 'vertical', color: 'gold', shape: 'rect', label: 'pay', height: 42 },
    createOrder: async () => {
      const res = await ($fetch('/api/paypal/create-order-kisses', {
        method: 'POST', body: { taglioId: taglioScelto.value?.id },
      })) as { orderID: string }
      return res.orderID
    },
    onApprove: async (data: any) => {
      ppState.value = 'loading'
      try {
        const token = await authStore.user?.getIdToken()
        const result = await ($fetch('/api/paypal/capture-order-kisses', {
          method: 'POST',
          headers: { Authorization: `Bearer ${token}` },
          body: { orderID: data.orderID, uid: authStore.user?.uid, taglioId: taglioScelto.value?.id },
        })) as { kissesAdded?: number }
        const added = result.kissesAdded ?? taglioScelto.value?.kisses ?? 0
        kisses.value += added
        emit('kissesUpdate', kisses.value)
        emit('profileUpdate', { kisses: kisses.value })
        ppState.value = 'idle'
        flash('💖 ' + t('modal.kisses_added_msg', { n: added }))
      } catch (e: any) {
        ppErr.value = e?.message ?? t('shop.purchase_error'); ppState.value = 'error'
      }
    },
    onError: (err: any) => { console.error('[PayPal shop]', err); ppErr.value = t('modal.paypal_error'); ppState.value = 'error' },
    onCancel: () => { /* chiuso da PayPal */ },
  }).render(ppRef.value)
}
function loadPayPal() {
  const clientId = (config.public as any).paypalClientId
  if (!clientId) { ppErr.value = t('modal.paypal_config_missing'); ppState.value = 'error'; return }
  if ((window as any).paypal) { ppRendered.value = false; renderPayPal(); return }
  const id = 'paypal-sdk-shop'
  if (document.getElementById(id)) return
  const script = document.createElement('script')
  script.id = id
  script.src = `https://www.paypal.com/sdk/js?client-id=${clientId}&currency=EUR&locale=it_IT&disable-funding=credit,card`
  script.onload = () => renderPayPal()
  script.onerror = () => { ppErr.value = t('modal.paypal_loading_error'); ppState.value = 'error' }
  document.head.appendChild(script)
}
watch(selTaglio, () => { ppRendered.value = false; if ((window as any).paypal) renderPayPal() })
onUnmounted(() => { document.getElementById('paypal-sdk-shop')?.remove() })
</script>

<template>
  <div class="neg-overlay" @click.self="emit('close')">
    <div class="neg-panel">
      <!-- Header -->
      <div class="neg-head">
        <span class="neg-title" :style="{ fontFamily: FF.display }">{{ $t('shop.title') }}</span>
        <div class="neg-kisses">
          <KissesIcon :size="14" />
          <span :style="{ fontFamily: FF.label, fontWeight: 900, color: 'var(--theme-accent-pink)' }">{{ kisses }}</span>
        </div>
        <button class="neg-close" @click="emit('close')" :style="{ fontFamily: FF.label }">✕</button>
      </div>

      <!-- Toast -->
      <Transition name="fade">
        <div v-if="notif" class="neg-toast"
          :style="{ background: `${notif.colore}20`, border: `1px solid ${notif.colore}55`, color: notif.colore, fontFamily: FF.label }">
          {{ notif.testo }}
        </div>
      </Transition>

      <AppLoading v-if="!caricato" />

      <div v-else class="neg-body">
        <!-- ── Beni con Kisses ── -->
        <div class="neg-section-title" :style="{ fontFamily: FF.label, color: C.sakura }">{{ $t('shop.buy_with_kisses') }}</div>
        <div class="neg-beni">
          <div v-for="b in beniList" :key="b.id" class="neg-bene">
            <span class="neg-bene-icon" :style="{ color: b.color, background: b.color + '1c' }">
              <component :is="b.icon" :size="18" stroke-width="2" />
            </span>
            <div class="neg-bene-txt">
              <div class="neg-bene-label" :style="{ fontFamily: FF.body }">{{ $t(b.titleKey) }}</div>
              <div class="neg-bene-desc" :style="{ fontFamily: FF.body }">{{ $t(b.descKey) }}</div>
            </div>
            <button
              class="neg-buy"
              :disabled="kisses < b.kisses || busy === b.id"
              :class="{ 'neg-buy--off': kisses < b.kisses }"
              :style="{ fontFamily: FF.label }"
              @click="acquistaBene(b.id)"
            >
              <template v-if="busy === b.id">…</template>
              <template v-else><KissesIcon :size="12" style="display:inline-block;vertical-align:-2px;" /> {{ b.kisses }}</template>
            </button>
          </div>
        </div>

        <div class="neg-divider" />

        <!-- ── Ricarica Kisses (PayPal) ── -->
        <div class="neg-section-title" :style="{ fontFamily: FF.label, color: C.gold }">{{ $t('shop.recharge_kisses') }}</div>
        <p class="neg-recharge-desc" :style="{ fontFamily: FF.body }">{{ $t('shop.recharge_desc') }}</p>

        <div class="neg-tagli">
          <button
            v-for="tg in tagli" :key="tg.id"
            @click="selTaglio = tg.id"
            class="neg-taglio"
            :class="{ 'neg-taglio--sel': selTaglio === tg.id }"
          >
            <div class="neg-taglio-k">
              <KissesIcon :size="13" />
              <span :style="{ fontFamily: FF.display }">{{ tg.kisses }}</span>
            </div>
            <div class="neg-taglio-price" :style="{ fontFamily: FF.label, color: C.gold }">€{{ tg.price_eur }}</div>
            <div v-if="(tg.bonus ?? 0) > 0" class="neg-taglio-bonus" :style="{ fontFamily: FF.body, color: C.ok }">+{{ tg.bonus }} bonus</div>
          </button>
        </div>

        <!-- PayPal -->
        <div class="neg-paypal">
          <div v-if="ppState === 'error'" class="neg-pp-msg" :style="{ color: C.err, fontFamily: FF.label }">{{ ppErr }}</div>
          <div v-else-if="ppState === 'loading'" class="neg-pp-msg" :style="{ fontFamily: FF.label }">{{ $t('modal.completing_purchase') }}</div>
          <div v-show="ppState === 'idle'" ref="ppRef" style="min-height:46px" />
        </div>
        <p class="neg-secure" :style="{ fontFamily: FF.body }">{{ $t('shop.secure_payment') }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.neg-overlay {
  position: fixed; inset: 0; z-index: 100;
  background: var(--theme-overlay); backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px);
  display: flex; align-items: flex-end; justify-content: center;
}
@media (min-width: 640px) { .neg-overlay { align-items: center; } }
.neg-panel {
  width: 100%; max-width: 440px; max-height: 92dvh;
  display: flex; flex-direction: column;
  background: var(--theme-surface);
  border: 1px solid var(--theme-border);
  border-radius: 22px 22px 0 0;
  box-shadow: 0 -8px 40px var(--theme-shadow);
  overflow: hidden;
  position: relative;
}
/* Da tablet in su: card centrata con margini laterali garantiti */
@media (min-width: 640px) {
  .neg-panel { border-radius: 22px; max-width: min(440px, calc(100vw - 32px)); }
}

.neg-head {
  flex-shrink: 0; display: flex; align-items: center; gap: 10px;
  padding: 14px 16px; border-bottom: 1px solid var(--theme-border);
}
.neg-title { font-size: 15px; font-weight: 900; color: var(--theme-text); flex: 1; min-width: 0;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.neg-kisses {
  display: flex; align-items: center; gap: 5px;
  background: var(--theme-surface-2); border: 1px solid var(--theme-border);
  border-radius: 999px; padding: 5px 12px; font-size: 14px;
}
.neg-close {
  width: 34px; height: 34px; border-radius: 10px; flex-shrink: 0;
  background: var(--theme-surface-2); border: 1px solid var(--theme-border);
  color: var(--theme-text-2); font-size: 14px; cursor: pointer;
}

.neg-toast {
  position: absolute; top: 66px; left: 50%; transform: translateX(-50%);
  z-index: 5; padding: 8px 16px; border-radius: 12px;
  font-size: 12px; font-weight: 700; letter-spacing: 0.05em; white-space: nowrap;
}

.neg-body { flex: 1; overflow-y: auto; -webkit-overflow-scrolling: touch; padding: 18px; }

.neg-section-title {
  font-size: 12px; font-weight: 800; letter-spacing: 0.18em; text-transform: uppercase; margin-bottom: 12px;
}

.neg-beni { display: flex; flex-direction: column; gap: 9px; }
.neg-bene {
  display: flex; align-items: center; gap: 10px;
  background: var(--theme-surface-2); border: 1px solid var(--theme-border);
  border-radius: 14px; padding: 11px 12px;
}
.neg-bene-icon {
  width: 36px; height: 36px; border-radius: 11px; flex-shrink: 0;
  display: grid; place-items: center;
}
.neg-bene-txt { flex: 1; min-width: 0; }
.neg-bene-label { font-size: 12.5px; font-weight: 800; color: var(--theme-text); }
.neg-bene-desc { font-size: 10.5px; color: var(--theme-text-2); margin-top: 2px; line-height: 1.35; }
.neg-buy {
  flex-shrink: 0; padding: 8px 12px; border-radius: 999px; border: none; cursor: pointer;
  background: var(--theme-accent); color: #fff; font-size: 11.5px; font-weight: 800; letter-spacing: 0.03em;
  min-width: 66px; white-space: nowrap; transition: transform 0.12s, background 0.15s;
}
.neg-buy:hover:not(:disabled) { transform: translateY(-1px); }
.neg-buy--off { background: var(--theme-surface); color: var(--theme-text-3); cursor: not-allowed; border: 1px solid var(--theme-border); }

.neg-divider { height: 2px; background: var(--theme-border-2); opacity: 0.6; border-radius: 999px; margin: 22px 0 18px; }

.neg-recharge-desc { font-size: 12px; color: var(--theme-text-2); margin-bottom: 14px; line-height: 1.5; }
/* Sezione tagli: unica riga che scorre in ORIZZONTALE se non ci sta (solo
   questa sezione scrolla, non tutto il popup). Le card non si stringono. */
.neg-tagli {
  display: flex; gap: 10px; margin-bottom: 16px;
  overflow-x: auto; overflow-y: hidden;
  -webkit-overflow-scrolling: touch;
  padding-bottom: 4px; scroll-snap-type: x proximity;
}
.neg-tagli::-webkit-scrollbar { height: 4px; }
.neg-tagli::-webkit-scrollbar-thumb { background: var(--theme-border-2); border-radius: 999px; }
.neg-taglio {
  flex: 0 0 92px; scroll-snap-align: start;
  background: var(--theme-surface-2); border: 2px solid var(--theme-border);
  border-radius: 14px; padding: 11px 6px; text-align: center; cursor: pointer;
  transition: transform 0.12s, border-color 0.15s, box-shadow 0.15s;
}
.neg-taglio:hover { transform: translateY(-2px); }
.neg-taglio--sel { border-color: var(--theme-accent-pink); box-shadow: 0 0 14px rgba(217,70,168,0.28); }
.neg-taglio-k { display: flex; align-items: center; justify-content: center; gap: 3px; font-size: 15px; font-weight: 900; color: var(--theme-text); margin-bottom: 3px; }
.neg-taglio-price { font-size: 13px; font-weight: 800; }
.neg-taglio-bonus { font-size: 9px; margin-top: 3px; font-weight: 700; }

.neg-paypal { min-height: 46px; margin-bottom: 10px; }
.neg-pp-msg { text-align: center; font-size: 12px; padding: 12px 0; color: var(--theme-text-2); }
.neg-secure { font-size: 11px; color: var(--theme-text-3); text-align: center; }

.fade-enter-active, .fade-leave-active { transition: opacity 0.3s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>

// src/components/NegozioOverlay.jsx
'use client';
import { useState, useEffect, useRef, useCallback } from 'react';
import KissesIcon from './KissesIcon';
import KissesShortageModal from './KissesShortageModal';
import { getNegozioConfig } from '@/lib/firestoreService';

// Mapping esplicito beneId → endpoint (evita errori di auto-generazione)
const BENE_ENDPOINT = {
  pack_sfida: '/api/kisses/buy-pack',
  energia:    '/api/kisses/buy-energia',
  pass_hard:  '/api/kisses/buy-passhard',
};

const BENI_ICONS  = { pack_sfida: '🎁', energia: '⚡', pass_hard: '🔞' };
const BENI_COLORI = { pack_sfida: '#f5a623', energia: '#00e676', pass_hard: '#ec4899' };

function SezioneAcquistaBeni({ beni, kisses, user, onKissesUpdate, hardPass = false, onPassHard }) {
  const [busy, setBusy]         = useState(null);
  const [notif, setNotif]       = useState(null);
  const [shortage, setShortage] = useState(null);
  const [conferma, setConferma] = useState(null); // { beneId, costo, label }

  const mostra = (msg, ok = true) => { setNotif({ msg, ok }); setTimeout(() => setNotif(null), 2500); };

  const acquista = async (beneId) => {
    const endpoint = BENE_ENDPOINT[beneId];
    if (!endpoint) { mostra('Errore: bene non riconosciuto', false); return; }
    setBusy(beneId);
    try {
      const token = await user.getIdToken();
      const res = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${token}` } });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Errore acquisto');
      const spent = data.kissesCost ?? beni[beneId]?.kisses ?? 0;
      onKissesUpdate(Math.max(0, (kisses ?? 0) - spent));
      if (beneId === 'pass_hard') onPassHard?.();
      mostra(`✓ ${beni[beneId]?.label} acquistato!`);
    } catch (e) { mostra(e.message, false); }
    finally { setBusy(null); }
  };

  const onShortageSuccess = async (newKisses) => {
    onKissesUpdate(newKisses);
    const beneId = shortage.beneId;
    setShortage(null);
    setTimeout(() => acquista(beneId), 300);
  };

  return (
    <div>
      {/* Popup conferma acquisto */}
      {conferma && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 500,
          background: 'rgba(6,3,15,0.92)', backdropFilter: 'blur(16px)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
        }}>
          <div style={{ background: 'rgba(12,6,28,0.98)', border: '1px solid rgba(255,77,158,0.3)', borderRadius: 16, padding: '24px 28px', maxWidth: 320, width: '100%', textAlign: 'center' }}>
            <div style={{ fontFamily: 'Orbitron', fontSize: 12, color: '#ff4d9e', letterSpacing: 2, marginBottom: 10 }}>CONFERMA ACQUISTO</div>
            <div style={{ fontFamily: 'Fredoka', fontSize: 14, color: '#eedcd4', marginBottom: 6 }}>{conferma.label}</div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4, marginBottom: 18, fontSize: 13, color: '#ff4d9e', fontFamily: 'Orbitron', fontWeight: 700 }}>
              <KissesIcon size={14} /> {conferma.costo} Kisses
            </div>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button onClick={() => setConferma(null)} style={{ background: 'none', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 8, color: 'rgba(238,232,220,0.5)', fontFamily: 'Orbitron', fontSize: 9, padding: '9px 18px', cursor: 'pointer' }}>ANNULLA</button>
              <button onClick={() => { const id = conferma.beneId; setConferma(null); acquista(id); }} style={{ background: 'rgba(255,77,158,0.15)', border: '1px solid rgba(255,77,158,0.5)', borderRadius: 8, color: '#ff4d9e', fontFamily: 'Orbitron', fontSize: 9, padding: '9px 18px', cursor: 'pointer' }}>CONFERMA</button>
            </div>
          </div>
        </div>
      )}
      {shortage && (
        <KissesShortageModal
          missingKisses={shortage.missingKisses}
          currentKisses={kisses}
          user={user}
          onSuccess={onShortageSuccess}
          onCancel={() => setShortage(null)}
        />
      )}
      {notif && (
        <div style={{ marginBottom: 12, padding: '8px 14px', borderRadius: 8,
          background: notif.ok ? 'rgba(0,230,118,0.1)' : 'rgba(255,77,77,0.1)',
          border: `1px solid ${notif.ok ? 'rgba(0,230,118,0.4)' : 'rgba(255,77,77,0.4)'}`,
          color: notif.ok ? '#00e676' : '#ff4d4d',
          fontFamily: 'Orbitron', fontSize: 10, letterSpacing: 1,
        }}>{notif.msg}</div>
      )}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {Object.entries(beni || {}).map(([id, bene]) => {
          const colore = BENI_COLORI[id] || '#f5a623';
          const icon   = BENI_ICONS[id]  || '✦';
          const puoAcquistare = (kisses ?? 0) >= bene.kisses;
          return (
            <div key={id} style={{ background: 'rgba(6,3,15,0.6)', border: `1px solid ${colore}30`,
              borderRadius: 12, padding: '14px 16px',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <span style={{ fontSize: 22 }}>{icon}</span>
                <div>
                  <div style={{ fontFamily: 'Orbitron', fontSize: 11, color: colore, fontWeight: 700 }}>{bene.label}</div>
                  <div style={{ fontSize: 10, color: 'rgba(238,232,220,0.45)', fontFamily: 'Fredoka', marginTop: 2 }}>{bene.descrizione}</div>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 3 }}>
                  <KissesIcon size={13} /><span style={{ fontFamily: 'Orbitron', fontSize: 12, color: '#ff4d9e', fontWeight: 700 }}>{bene.kisses}</span>
                </div>
                <button onClick={() => {
                  if (busy === id) return;
                  if (id === 'pass_hard' && hardPass) return;
                  if ((kisses ?? 0) < bene.kisses) { setShortage({ beneId: id, missingKisses: bene.kisses - (kisses ?? 0) }); return; }
                  setConferma({ beneId: id, costo: bene.kisses, label: bene.label });
                }} disabled={busy === id || (id === 'pass_hard' && hardPass)} style={{
                  background: puoAcquistare ? `${colore}25` : 'rgba(255,255,255,0.04)',
                  border: `1px solid ${puoAcquistare ? colore + '60' : 'rgba(255,255,255,0.1)'}`,
                  borderRadius: 8, color: puoAcquistare ? colore : 'rgba(255,255,255,0.25)',
                  fontFamily: 'Orbitron', fontSize: 9, padding: '7px 14px',
                  cursor: busy === id ? 'wait' : 'pointer', letterSpacing: 1, transition: 'all 0.2s',
                }}>
                  {busy === id ? '…' : (id === 'pass_hard' && hardPass) ? '✓ ACQUISTATO' : puoAcquistare ? 'ACQUISTA' : `MANCANO ${bene.kisses - (kisses ?? 0)}`}
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function SezioneRicaricaKisses({ tagli, user, kisses, onKissesUpdate }) {
  const [selectedTaglio, setSelectedTaglio] = useState(tagli?.[1]?.id || 'sm');
  const [stato, setStato] = useState('idle');
  const [errMsg, setErrMsg] = useState('');
  const containerRef = useRef(null);
  const paypalRendered = useRef(false);
  const clientId = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID;
  const taglioScelto = tagli?.find(t => t.id === selectedTaglio) || tagli?.[0];

  const renderPayPal = useCallback(() => {
    if (!containerRef.current || !window.paypal || paypalRendered.current) return;
    paypalRendered.current = true;
    containerRef.current.innerHTML = '';
    window.paypal.Buttons({
      style: { layout: 'vertical', color: 'gold', shape: 'rect', label: 'pay', height: 44 },
      createOrder: async () => {
        const res = await fetch('/api/paypal/create-order-kisses', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ taglioId: taglioScelto.id }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Errore creazione ordine');
        return data.orderID;
      },
      onApprove: async (data) => {
        setStato('loading');
        try {
          const token = await user.getIdToken();
          const res = await fetch('/api/paypal/capture-order-kisses', {
            method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
            body: JSON.stringify({ orderID: data.orderID, uid: user.uid, taglioId: taglioScelto.id }),
          });
          const result = await res.json();
          if (!res.ok) throw new Error(result.error || 'Errore cattura');
          setStato('success');
          // newBalance calcolato localmente per evitare lettura Firestore aggiuntiva
          onKissesUpdate((kisses ?? 0) + (result.kissesAdded ?? taglioScelto?.kisses ?? 0));
        } catch (e) { setErrMsg(e.message); setStato('error'); }
      },
      onError: (err) => { console.error('[PayPal negozio]', err); setErrMsg('Errore PayPal. Riprova.'); setStato('error'); },
    }).render(containerRef.current);
  }, [taglioScelto, user]);

  useEffect(() => {
    if (!clientId) { setErrMsg('PayPal non configurato.'); setStato('error'); return; }
    const load = () => { paypalRendered.current = false; renderPayPal(); };
    if (window.paypal) { load(); return; }
    if (document.getElementById('paypal-sdk') || document.getElementById('paypal-sdk-negozio')) { if (window.paypal) load(); return; }
    const script = document.createElement('script');
    script.id = 'paypal-sdk-negozio';
    script.src = `https://www.paypal.com/sdk/js?client-id=${clientId}&currency=EUR&locale=it_IT&disable-funding=credit,card`;
    script.onload = load;
    script.onerror = () => { setErrMsg('Impossibile caricare PayPal.'); setStato('error'); };
    document.head.appendChild(script);
  }, []);

  useEffect(() => { paypalRendered.current = false; if (window.paypal) renderPayPal(); }, [selectedTaglio]);

  if (stato === 'success') return (
    <div style={{ textAlign: 'center', padding: '24px 0' }}>
      <div style={{ fontSize: 36, marginBottom: 8 }}>💖</div>
      <div style={{ fontFamily: 'Orbitron', fontSize: 11, color: '#00e676', letterSpacing: 2, marginBottom: 4 }}>KISSES ACQUISTATI!</div>
      <div style={{ fontFamily: 'Fredoka', fontSize: 12, color: 'rgba(238,232,220,0.6)' }}>+{taglioScelto?.kisses} Kisses aggiunti al tuo saldo</div>
      <button onClick={() => { setStato('idle'); paypalRendered.current = false; setTimeout(renderPayPal, 100); }}
        style={{ marginTop: 12, background: 'rgba(255,77,158,0.12)', border: '1px solid rgba(255,77,158,0.4)', borderRadius: 8, color: '#ff4d9e', fontFamily: 'Orbitron', fontSize: 9, padding: '7px 14px', cursor: 'pointer' }}>
        ACQUISTA ANCORA
      </button>
    </div>
  );

  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 8, marginBottom: 14 }}>
        {(tagli || []).map(t => {
          const sel = t.id === selectedTaglio;
          return (
            <div key={t.id} onClick={() => setSelectedTaglio(t.id)} style={{
              padding: '10px 8px', borderRadius: 10, cursor: 'pointer', textAlign: 'center',
              background: sel ? 'rgba(255,77,158,0.15)' : 'rgba(6,3,15,0.6)',
              border: `2px solid ${sel ? '#ff4d9e' : 'rgba(255,77,158,0.2)'}`,
              transition: 'all 0.2s', boxShadow: sel ? '0 0 12px rgba(255,77,158,0.3)' : 'none',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 3, marginBottom: 3 }}>
                <KissesIcon size={13} /><span style={{ fontFamily: 'Orbitron', fontSize: 13, color: sel ? '#ff4d9e' : '#eedcd4', fontWeight: 900 }}>{t.kisses}</span>
              </div>
              <div style={{ fontFamily: 'Orbitron', fontSize: 11, color: '#f5a623', fontWeight: 700 }}>€{t.price_eur}</div>
              {t.bonus && <div style={{ fontSize: 9, color: '#00e676', marginTop: 2, fontFamily: 'Fredoka' }}>{t.bonus}</div>}
            </div>
          );
        })}
      </div>
      {stato === 'error' && <div style={{ color: '#ff4d4d', fontFamily: 'Orbitron', fontSize: 9, textAlign: 'center', marginBottom: 8 }}>{errMsg}</div>}
      {stato === 'loading' && <div style={{ color: 'rgba(238,232,220,0.5)', fontFamily: 'Orbitron', fontSize: 9, textAlign: 'center', marginBottom: 8 }}>Elaborazione…</div>}
      <div ref={containerRef} style={{ minHeight: 50 }} />
    </div>
  );
}

export default function NegozioOverlay({ user, profilo: profiloInit, onKissesUpdate, onClose }) {
  const [config, setConfig] = useState(null);
  const [kisses, setKisses] = useState(profiloInit?.kisses ?? 0);
  const [hardPass, setHardPass] = useState(profiloInit?.hardPass ?? false);

  useEffect(() => { getNegozioConfig().then(setConfig); }, []);

  const handleKisses = (newKisses) => { setKisses(newKisses); onKissesUpdate(newKisses); };
  const handlePassHard = () => { setHardPass(true); };

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 300,
      background: 'rgba(6,3,15,0.98)', backdropFilter: 'blur(20px)',
      overflowY: 'auto', display: 'flex', flexDirection: 'column',
    }}>
      {/* Header */}
      <div style={{ position: 'sticky', top: 0, zIndex: 10, background: 'rgba(6,3,15,0.97)', backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(245,166,35,0.12)', padding: '12px 18px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button onClick={onClose} style={{ background: 'none', border: '1px solid rgba(245,166,35,0.3)', borderRadius: 7,
            color: '#f5a623', fontFamily: 'Orbitron', fontSize: 9, padding: '6px 12px', cursor: 'pointer' }}>← INDIETRO</button>
          <div style={{ fontFamily: 'Orbitron', fontSize: 14, fontWeight: 900, color: '#f5a623', letterSpacing: 3 }}>🛒 NEGOZIO</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <KissesIcon size={16} />
          <span style={{ fontFamily: 'Orbitron', fontSize: 14, fontWeight: 800, color: '#ff4d9e' }}>{kisses}</span>
        </div>
      </div>

      <div style={{ maxWidth: 480, margin: '0 auto', padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 24, width: '100%' }}>
        {!config ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'rgba(238,232,220,0.35)', fontFamily: 'Orbitron', fontSize: 10 }}>CARICAMENTO…</div>
        ) : (
          <>
            <div>
              <div style={{ fontFamily: 'Orbitron', fontSize: 10, letterSpacing: 3, color: 'rgba(238,232,220,0.4)', marginBottom: 12 }}>ACQUISTA CON KISSES</div>
              <SezioneAcquistaBeni beni={config.beni} kisses={kisses} user={user} onKissesUpdate={handleKisses} hardPass={hardPass} onPassHard={handlePassHard} />
            </div>
            <div style={{ height: 1, background: 'linear-gradient(90deg, transparent, rgba(255,77,158,0.3), transparent)' }} />
            <div>
              <div style={{ fontFamily: 'Orbitron', fontSize: 10, letterSpacing: 3, color: 'rgba(238,232,220,0.4)', marginBottom: 4 }}>RICARICA KISSES</div>
              <div style={{ fontFamily: 'Fredoka', fontSize: 11, color: 'rgba(238,232,220,0.35)', marginBottom: 14 }}>Acquista Kisses con PayPal e usali per beni di gioco e Pesca Misteriosa</div>
              <SezioneRicaricaKisses tagli={config.tagli_kisses} user={user} kisses={kisses} onKissesUpdate={handleKisses} />
            </div>
          </>
        )}
      </div>
    </div>
  );
}
