// pages/negozio.vue
<!-- ============================================================
  Pagina negozio: acquisto beni con Kisses e ricarica Kisses via PayPal.
  Equivalente di src/app/negozio/page.jsx nel Next.js originale.
  ============================================================ -->
<script setup lang="ts">
import { useAuthStore }             from '~/stores/auth'
import { useGameStore }             from '~/stores/game'
import { getUserProfile }           from '~/utils/firestoreService'

definePageMeta({ middleware: 'auth' })

const authStore = useAuthStore()
const gameStore = useGameStore()
const router    = useRouter()
const config    = useRuntimeConfig()

const prezzi       = ref<Record<string, unknown> | null>(null)
const kisses       = ref(gameStore.profilo?.kisses ?? 0)
const caricato     = ref(false)
const notif        = ref<{ testo: string; colore: string } | null>(null)

const PAYPAL_CLIENT_ID = (config.public as Record<string, unknown>).paypalClientId as string

onMounted(async () => {
  if (!authStore.user) return
  const profilo = await getUserProfile(authStore.user.uid)
  if (!profilo) { router.replace('/onboarding'); return }
  kisses.value = profilo.kisses ?? 0
  // Carica prezzi dal server
  try {
    const token = await authStore.user.getIdToken()
    const data  = await $fetch<{ prezzi: Record<string, unknown> }>('/api/negozio/config', {
      headers: { Authorization: `Bearer ${token}` },
    })
    prezzi.value = data.prezzi
  } catch {
    // Usa default
    prezzi.value = {
      beni: {
        pack_sfida:  { kisses: 50,  label: '🎁 Pack Sfida',   descrizione: '+1 pacchetto sfida' },
        energia:     { kisses: 20,  label: '⚡ Energia',      descrizione: 'Ricarica 10 unità energia' },
        pass_hard:   { kisses: 500, label: '🔞 Hard Pass',    descrizione: 'Sblocca carte Hot' },
        trade_pass:  { kisses: 100, label: '🔄 Trade Pass',   descrizione: 'Scambi illimitati per sempre' },
      },
      tagli_kisses: [
        { id: 'xs', kisses: 100,  bonus: '',              price_eur: '0.99' },
        { id: 'sm', kisses: 300,  bonus: '+30 Kisses',    price_eur: '2.49' },
        { id: 'md', kisses: 600,  bonus: '+80 Kisses',    price_eur: '3.99' },
        { id: 'lg', kisses: 1400, bonus: '+200 Kisses',   price_eur: '7.99' },
      ],
    }
  }
  caricato.value = true
})

function flash(testo: string, colore = '#06d6a0') {
  notif.value = { testo, colore }
  setTimeout(() => (notif.value = null), 2500)
}

async function acquistaBene(beneId: string) {
  if (!authStore.user) return
  const costo = (prezzi.value?.beni as Record<string, { kisses: number }>)?.[beneId]?.kisses ?? 0
  if ((kisses.value ?? 0) < costo) {
    flash(`Kisses insufficienti — servono ${costo}`, '#ff4d4d')
    return
  }
  try {
    const token    = await authStore.user.getIdToken()
    const endpoint = beneId === 'pack_sfida'  ? '/api/kisses/buy-pack'
                   : beneId === 'energia'     ? '/api/kisses/buy-energia'
                   : beneId === 'pass_hard'   ? '/api/kisses/buy-passhard'
                   : beneId === 'trade_pass'  ? '/api/kisses/buy-tradepass'
                   : null
    if (!endpoint) return
    const data = await $fetch<{ kissesCost: number; newKisses?: number }>(endpoint, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
    })
    kisses.value -= data.kissesCost
    gameStore.setKisses(kisses.value)
    const label = (prezzi.value?.beni as Record<string, { label: string }>)?.[beneId]?.label ?? beneId
    flash(`✓ ${label} acquistato!`)
  } catch (e: unknown) {
    flash((e as { data?: { message?: string } })?.data?.message ?? 'Errore acquisto', '#ff4d4d')
  }
}
</script>

<template>
  <div class="min-h-screen" style="background:rgb(6,3,15);padding-bottom:40px">

    <!-- Caricamento -->
    <div v-if="!caricato" class="min-h-screen flex items-center justify-center">
      <div class="text-4xl text-pink-400 font-orbitron">♥</div>
    </div>

    <template v-else>
      <!-- Header -->
      <header class="sticky top-0 z-50 flex items-center justify-between px-4 py-3"
              style="background:rgba(6,3,15,0.95);backdrop-filter:blur(20px);
                     border-bottom:1px solid rgba(245,166,35,0.12)">
        <div class="flex items-center gap-3">
          <button
            class="border rounded-lg text-amber-400 font-orbitron text-[9px] px-3 py-1.5 cursor-pointer bg-transparent"
            style="border-color:rgba(245,166,35,0.3)"
            @click="router.push('/gioco')"
          >← GIOCO</button>
          <span class="font-orbitron text-sm font-black text-amber-400 tracking-widest">🛒 NEGOZIO</span>
        </div>
        <div class="flex items-center gap-1">
          <span class="text-pink-400 text-sm">💋</span>
          <span class="font-orbitron text-sm font-black text-pink-400">{{ kisses }}</span>
        </div>
      </header>

      <!-- Notifica -->
      <Transition name="fade">
        <div v-if="notif" class="fixed top-16 left-1/2 -translate-x-1/2 z-50 px-4 py-2 rounded-lg text-xs font-orbitron tracking-wider"
             :style="{ background: `${notif.colore}15`, border: `1px solid ${notif.colore}40`, color: notif.colore }">
          {{ notif.testo }}
        </div>
      </Transition>

      <div class="max-w-[480px] mx-auto px-4 py-5 flex flex-col gap-6">

        <!-- Beni con Kisses -->
        <section>
          <div class="font-orbitron text-[11px] tracking-widest mb-3" style="color:rgba(238,232,220,0.4)">
            ACQUISTA CON KISSES
          </div>
          <div class="flex flex-col gap-2.5">
            <div
              v-for="(bene, id) in (prezzi?.beni as Record<string, {kisses: number; label: string; descrizione?: string}>)"
              :key="id"
              class="flex items-center justify-between gap-3 rounded-xl px-4 py-3.5"
              style="background:rgba(6,3,15,0.6);border:1px solid rgba(245,166,35,0.18)"
            >
              <div class="flex items-center gap-3">
                <span class="text-2xl">{{ id === 'pack_sfida' ? '🎁' : id === 'energia' ? '⚡' : id === 'pass_hard' ? '🔞' : '🔄' }}</span>
                <div>
                  <div class="font-orbitron text-xs font-bold text-amber-400">{{ bene.label }}</div>
                  <div class="font-fredoka text-[10px] mt-0.5" style="color:rgba(238,232,220,0.45)">{{ bene.descrizione }}</div>
                </div>
              </div>
              <div class="flex items-center gap-2 shrink-0">
                <span class="font-orbitron text-xs text-pink-400 font-bold">💋 {{ bene.kisses }}</span>
                <button
                  class="font-orbitron text-[9px] px-3 py-1.5 rounded-lg cursor-pointer transition-all"
                  :class="kisses >= bene.kisses
                    ? 'text-amber-400 hover:opacity-80'
                    : 'opacity-30 cursor-not-allowed'"
                  :style="kisses >= bene.kisses
                    ? 'background:rgba(245,166,35,0.15);border:1px solid rgba(245,166,35,0.4)'
                    : 'background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.1);color:rgba(255,255,255,0.25)'"
                  @click="acquistaBene(id)"
                >
                  {{ kisses >= bene.kisses ? 'ACQUISTA' : `MANCANO ${bene.kisses - kisses}` }}
                </button>
              </div>
            </div>
          </div>
        </section>

        <div class="h-px" style="background:linear-gradient(90deg,transparent,rgba(255,77,158,0.3),transparent)" />

        <!-- Ricarica Kisses con PayPal -->
        <section>
          <div class="font-orbitron text-[11px] tracking-widest mb-1" style="color:rgba(238,232,220,0.4)">
            RICARICA KISSES
          </div>
          <div class="font-fredoka text-xs mb-4" style="color:rgba(238,232,220,0.35)">
            Acquista Kisses con PayPal e usali per beni di gioco e Pesca Misteriosa
          </div>

          <!-- Taglie Kisses -->
          <div class="grid grid-cols-2 gap-2.5 mb-4">
            <div
              v-for="taglio in (prezzi?.tagli_kisses as any[])"
              :key="taglio.id"
              class="p-3 rounded-xl text-center cursor-pointer transition-all"
              style="background:rgba(6,3,15,0.6);border:2px solid rgba(255,77,158,0.2)"
            >
              <div class="flex items-center justify-center gap-1 mb-1">
                <span class="text-pink-400 text-sm">💋</span>
                <span class="font-orbitron text-sm text-amber-50 font-black">{{ taglio.kisses }}</span>
              </div>
              <div class="font-orbitron text-xs text-amber-400 font-bold">€{{ taglio.price_eur }}</div>
              <div v-if="taglio.bonus" class="text-[9px] text-green-400 mt-0.5 font-fredoka">{{ taglio.bonus }}</div>
            </div>
          </div>

          <div class="font-fredoka text-xs text-center" style="color:rgba(238,232,220,0.4)">
            Pagamento sicuro via PayPal
          </div>
        </section>
      </div>
    </template>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.3s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>

// src/app/negozio/page.jsx
'use client';
import { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/AuthContext';
import { getUserProfile, getNegozioConfig } from '@/lib/firestoreService';
import KissesIcon from '@/components/KissesIcon';
import KissesShortageModal from '@/components/KissesShortageModal';

const RARITA_BG = { pack_sfida: '#f5a623', energia: '#00e676', pass_hard: '#ec4899' };
const BENI_ICONS = { pack_sfida: '🎁', energia: '⚡', pass_hard: '🔞' };

function SezioneAcquistaBeni({ beni, kisses, user, onKissesUpdate }) {
  const [busy, setBusy] = useState(null);
  const [notif, setNotif] = useState(null);
  const [shortage, setShortage] = useState(null); // { beneId, missingKisses, costo }

  const mostra = (msg, ok = true) => {
    setNotif({ msg, ok });
    setTimeout(() => setNotif(null), 2500);
  };

  const acquista = async (beneId) => {
    const costo = beni[beneId]?.kisses ?? 0;
    if ((kisses ?? 0) < costo) {
      setShortage({ beneId, missingKisses: costo - (kisses ?? 0), costo });
      return;
    }
    setBusy(beneId);
    try {
      const token = await user.getIdToken();
      const endpoint = `/api/kisses/buy-${beneId.replace('_', '-')}`;
      const res = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${token}` } });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Errore acquisto');
      onKissesUpdate(data.newKisses);
      mostra(`✓ ${beni[beneId]?.label} acquistato!`);
    } catch (e) { mostra(e.message, false); }
    finally { setBusy(null); }
  };

  const onShortageSuccess = async (newKisses) => {
    onKissesUpdate(newKisses);
    const { beneId } = shortage;
    setShortage(null);
    // Riprende automaticamente l'acquisto dopo aver ricaricato i Kisses
    setTimeout(() => acquista(beneId), 300);
  };

  const beniList = Object.entries(beni || {});
  return (
    <div>
      {shortage && (
        <KissesShortageModal
          missingKisses={shortage.missingKisses}
          currentKisses={kisses}
          onSuccess={onShortageSuccess}
          onCancel={() => setShortage(null)}
          user={user}
        />
      )}
      {notif && (
        <div style={{
          marginBottom: 12, padding: '8px 14px', borderRadius: 8,
          background: notif.ok ? 'rgba(0,230,118,0.1)' : 'rgba(255,77,77,0.1)',
          border: `1px solid ${notif.ok ? 'rgba(0,230,118,0.4)' : 'rgba(255,77,77,0.4)'}`,
          color: notif.ok ? '#00e676' : '#ff4d4d',
          fontFamily: 'Orbitron', fontSize: 10, letterSpacing: 1,
        }}>{notif.msg}</div>
      )}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {beniList.map(([id, bene]) => {
          const colore = RARITA_BG[id] || '#f5a623';
          const icon = BENI_ICONS[id] || '✦';
          const puoAcquistare = (kisses ?? 0) >= bene.kisses;
          return (
            <div key={id} style={{
              background: 'rgba(6,3,15,0.6)',
              border: `1px solid ${colore}30`,
              borderRadius: 12, padding: '14px 16px',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <span style={{ fontSize: 24 }}>{icon}</span>
                <div>
                  <div style={{ fontFamily: 'Orbitron', fontSize: 11, color: colore, fontWeight: 700 }}>{bene.label}</div>
                  <div style={{ fontSize: 10, color: 'rgba(238,232,220,0.45)', fontFamily: 'Fredoka', marginTop: 2 }}>{bene.descrizione}</div>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 3 }}>
                  <KissesIcon size={13} />
                  <span style={{ fontFamily: 'Orbitron', fontSize: 12, color: '#ff4d9e', fontWeight: 700 }}>{bene.kisses}</span>
                </div>
                <button
                  onClick={() => acquista(id)}
                  disabled={busy === id}
                  style={{
                    background: puoAcquistare ? `rgba(${colore.slice(1).match(/.{2}/g).map(h => parseInt(h, 16)).join(',')},0.15)` : 'rgba(255,255,255,0.04)',
                    border: `1px solid ${puoAcquistare ? colore + '60' : 'rgba(255,255,255,0.1)'}`,
                    borderRadius: 8, color: puoAcquistare ? colore : 'rgba(255,255,255,0.25)',
                    fontFamily: 'Orbitron', fontSize: 9, padding: '7px 14px',
                    cursor: busy === id ? 'wait' : 'pointer',
                    letterSpacing: 1, transition: 'all 0.2s',
                  }}
                >
                  {busy === id ? '…' : puoAcquistare ? 'ACQUISTA' : `MANCANO ${bene.kisses - (kisses ?? 0)}`}
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function SezioneRicaricaKisses({ tagli, user, onKissesUpdate }) {
  const [selectedTaglio, setSelectedTaglio] = useState(tagli?.[1]?.id || 'sm');
  const [stato, setStato] = useState('idle');
  const [errMsg, setErrMsg] = useState('');
  const containerRef = useRef(null);
  const paypalRendered = useRef(false);
  const clientId = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID;
  const taglioScelto = tagli?.find(t => t.id === selectedTaglio) || tagli?.[0];

  const renderPayPal = useCallback(() => {
    if (!containerRef.current || !window.paypal || paypalRendered.current) return;
    paypalRendered.current = true;
    containerRef.current.innerHTML = '';
    window.paypal.Buttons({
      style: { layout: 'vertical', color: 'gold', shape: 'rect', label: 'pay', height: 44 },
      createOrder: async () => {
        const res = await fetch('/api/paypal/create-order-kisses', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ taglioId: taglioScelto.id }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Errore');
        return data.orderID;
      },
      onApprove: async (data) => {
        setStato('loading');
        try {
          const token = await user.getIdToken();
          const res = await fetch('/api/paypal/capture-order-kisses', {
            method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
            body: JSON.stringify({ orderID: data.orderID, uid: user.uid, taglioId: taglioScelto.id }),
          });
          const result = await res.json();
          if (!res.ok) throw new Error(result.error || 'Errore cattura');
          setStato('success');
          onKissesUpdate(result.newBalance);
        } catch (e) { setErrMsg(e.message); setStato('error'); }
      },
      onError: (err) => { console.error('[PayPal negozio]', err); setErrMsg('Errore PayPal. Riprova.'); setStato('error'); },
    }).render(containerRef.current);
  }, [taglioScelto, user]);

  useEffect(() => {
    if (!clientId) { setErrMsg('PayPal non configurato.'); setStato('error'); return; }
    const existingScript = document.getElementById('paypal-sdk');
    const existingScript2 = document.getElementById('paypal-sdk-negozio');
    const load = () => { paypalRendered.current = false; renderPayPal(); };
    if ((existingScript || existingScript2) && window.paypal) { load(); return; }
    const script = document.createElement('script');
    script.id = 'paypal-sdk-negozio';
    script.src = `https://www.paypal.com/sdk/js?client-id=${clientId}&currency=EUR&locale=it_IT&disable-funding=credit,card`;
    script.onload = load;
    script.onerror = () => { setErrMsg('Impossibile caricare PayPal.'); setStato('error'); };
    document.head.appendChild(script);
  }, []);

  useEffect(() => { paypalRendered.current = false; if (window.paypal) renderPayPal(); }, [selectedTaglio]);

  if (stato === 'success') {
    return (
      <div style={{ textAlign: 'center', padding: '24px 0' }}>
        <div style={{ fontSize: 40, marginBottom: 10 }}>💖</div>
        <div style={{ fontFamily: 'Orbitron', fontSize: 12, color: '#00e676', letterSpacing: 2, marginBottom: 6 }}>KISSES ACQUISTATI!</div>
        <div style={{ fontFamily: 'Fredoka', fontSize: 13, color: 'rgba(238,232,220,0.6)' }}>+{taglioScelto?.kisses} Kisses aggiunti al tuo saldo</div>
        <button onClick={() => { setStato('idle'); paypalRendered.current = false; setTimeout(renderPayPal, 100); }}
          style={{ marginTop: 14, background: 'rgba(255,77,158,0.12)', border: '1px solid rgba(255,77,158,0.4)', borderRadius: 8, color: '#ff4d9e', fontFamily: 'Orbitron', fontSize: 9, padding: '8px 16px', cursor: 'pointer' }}>
          ACQUISTA ANCORA
        </button>
      </div>
    );
  }

  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 10, marginBottom: 16 }}>
        {(tagli || []).map(t => {
          const sel = t.id === selectedTaglio;
          return (
            <div key={t.id} onClick={() => setSelectedTaglio(t.id)} style={{
              padding: '12px 10px', borderRadius: 10, cursor: 'pointer', textAlign: 'center',
              background: sel ? 'rgba(255,77,158,0.15)' : 'rgba(6,3,15,0.6)',
              border: `2px solid ${sel ? '#ff4d9e' : 'rgba(255,77,158,0.2)'}`,
              transition: 'all 0.2s',
              boxShadow: sel ? '0 0 14px rgba(255,77,158,0.3)' : 'none',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4, marginBottom: 4 }}>
                <KissesIcon size={14} />
                <span style={{ fontFamily: 'Orbitron', fontSize: 14, color: sel ? '#ff4d9e' : '#eedcd4', fontWeight: 900 }}>{t.kisses}</span>
              </div>
              <div style={{ fontFamily: 'Orbitron', fontSize: 12, color: '#f5a623', fontWeight: 700 }}>€{t.price_eur}</div>
              {t.bonus && <div style={{ fontSize: 9, color: '#00e676', marginTop: 3, fontFamily: 'Fredoka' }}>{t.bonus}</div>}
            </div>
          );
        })}
      </div>

      {stato === 'error' ? (
        <div style={{ color: '#ff4d4d', fontFamily: 'Orbitron', fontSize: 9, textAlign: 'center', marginBottom: 10 }}>{errMsg}</div>
      ) : stato === 'loading' ? (
        <div style={{ color: 'rgba(238,232,220,0.5)', fontFamily: 'Orbitron', fontSize: 9, textAlign: 'center', marginBottom: 10 }}>Elaborazione pagamento…</div>
      ) : null}

      <div ref={containerRef} style={{ minHeight: 50 }} />
    </div>
  );
}

export default function NegozioPage() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const [profilo, setProfilo] = useState(null);
  const [config, setConfig] = useState(null);
  const [kisses, setKisses] = useState(0);

  useEffect(() => {
    if (!loading && !user) { router.replace('/login'); return; }
    if (user) {
      Promise.all([getUserProfile(user.uid), getNegozioConfig()]).then(([p, c]) => {
        if (!p) { router.replace('/onboarding'); return; }
        setProfilo(p);
        setKisses(p.kisses ?? 0);
        setConfig(c);
      });
    }
  }, [user, loading]);

  if (loading || !profilo || !config) return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgb(6,3,15)' }}>
      <div style={{ fontSize: 36, color: '#ff4d9e', fontFamily: 'Orbitron' }}>♥</div>
    </div>
  );

  return (
    <div style={{ minHeight: '100vh', background: 'rgb(6,3,15)', padding: '0 0 40px' }}>
      {/* Header */}
      <div style={{
        position: 'sticky', top: 0, zIndex: 50,
        background: 'rgba(6,3,15,0.95)', backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(245,166,35,0.12)',
        padding: '12px 18px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button onClick={() => router.push('/gioco')} style={{
            background: 'none', border: '1px solid rgba(245,166,35,0.3)', borderRadius: 7,
            color: '#f5a623', fontFamily: 'Orbitron', fontSize: 9, padding: '6px 12px', cursor: 'pointer',
          }}>← GIOCO</button>
          <div style={{ fontFamily: 'Orbitron', fontSize: 14, fontWeight: 900, color: '#f5a623', letterSpacing: 3 }}>🛒 NEGOZIO</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <KissesIcon size={16} />
          <span style={{ fontFamily: 'Orbitron', fontSize: 14, fontWeight: 800, color: '#ff4d9e' }}>{kisses}</span>
        </div>
      </div>

      <div style={{ maxWidth: 480, margin: '0 auto', padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 24 }}>

        {/* Sezione beni con Kisses */}
        <div>
          <div style={{ fontFamily: 'Orbitron', fontSize: 11, letterSpacing: 3, color: 'rgba(238,232,220,0.4)', marginBottom: 12 }}>
            ACQUISTA CON KISSES
          </div>
          <SezioneAcquistaBeni
            beni={config.beni}
            kisses={kisses}
            user={user}
            onKissesUpdate={setKisses}
          />
        </div>

        {/* Divisore */}
        <div style={{ height: 1, background: 'linear-gradient(90deg, transparent, rgba(255,77,158,0.3), transparent)' }} />

        {/* Sezione ricarica Kisses */}
        <div>
          <div style={{ fontFamily: 'Orbitron', fontSize: 11, letterSpacing: 3, color: 'rgba(238,232,220,0.4)', marginBottom: 4 }}>
            RICARICA KISSES
          </div>
          <div style={{ fontFamily: 'Fredoka', fontSize: 11, color: 'rgba(238,232,220,0.35)', marginBottom: 14 }}>
            Acquista Kisses con PayPal e usali per beni di gioco e Pesca Misteriosa
          </div>
          <SezioneRicaricaKisses
            tagli={config.tagli_kisses}
            user={user}
            onKissesUpdate={setKisses}
          />
        </div>
      </div>
    </div>
  );
}
