// src/components/swap/SwapRewardToast.jsx
'use client';
import { useEffect, useState } from 'react';
import { C, FF } from '@/app/gioco/_redesign/_shared';
import KissesIcon from '@/components/KissesIcon';

export default function SwapRewardToast({ amount, streakDays, multiplier, type, message, onDone }) {
  const [visible, setVisible] = useState(true);
  useEffect(() => {
    const t = setTimeout(() => { setVisible(false); setTimeout(onDone, 350); }, 2500);
    return () => clearTimeout(t);
  }, []);

  const isLimit = type === 'limit';

  return (
    <div style={{
      position: 'fixed', top: 80, left: '50%', transform: `translateX(-50%) ${visible ? 'translateY(0)' : 'translateY(-24px)'}`,
      opacity: visible ? 1 : 0, transition: 'all 0.35s cubic-bezier(0.34,1.56,0.64,1)',
      background: 'rgba(6,3,15,0.96)', backdropFilter: 'blur(16px)',
      border: `1px solid ${isLimit ? 'rgba(255,91,108,0.4)' : 'rgba(245,197,96,0.4)'}`,
      borderRadius: 16, padding: '12px 20px',
      display: 'flex', alignItems: 'center', gap: 10,
      boxShadow: '0 8px 32px rgba(3,2,12,0.6)',
      zIndex: 500, whiteSpace: 'nowrap', maxWidth: '90vw',
    }}>
      {isLimit ? (
        <span style={{ fontFamily: FF.body, fontSize: 13, color: 'rgba(255,91,108,0.9)' }}>{message}</span>
      ) : (
        <>
          <KissesIcon size={18} />
          <span style={{ fontFamily: FF.display, fontSize: 20, color: C.gold, fontWeight: 800 }}>+{amount}</span>
          {multiplier > 1 && (
            <span style={{ fontFamily: FF.label, fontSize: 10, letterSpacing: '0.15em', color: C.aqua, textTransform: 'uppercase' }}>
              ×{multiplier.toFixed(1)} streak {streakDays}d
            </span>
          )}
        </>
      )}
    </div>
  );
}

// components/swap/SwapRewardToast.vue
<!-- Toast di notifica che appare dopo aver guadagnato Kisses tramite il sistema Swap -->
<script setup lang="ts">
defineProps<{
  amount?: number
  streakDays?: number
  multiplier?: number
  type?: string
  message?: string
}>()
const emit = defineEmits<{ done: [] }>()

const visible = ref(true)
onMounted(() => {
  const t = setTimeout(() => {
    visible.value = false
    setTimeout(() => emit('done'), 350)
  }, 2500)
  onUnmounted(() => clearTimeout(t))
})
</script>

<template>
  <div :style="{
    position:'fixed', top:'80px', left:'50%',
    transform:`translateX(-50%) ${visible ? 'translateY(0)' : 'translateY(-24px)'}`,
    opacity: visible ? 1 : 0, transition:'all 0.35s cubic-bezier(0.34,1.56,0.64,1)',
    background:'rgba(6,3,15,0.96)', backdropFilter:'blur(16px)',
    border:`1px solid ${type === 'limit' ? 'rgba(255,91,108,0.4)' : 'rgba(245,197,96,0.4)'}`,
    borderRadius:'16px', padding:'12px 20px',
    display:'flex', alignItems:'center', gap:'10px',
    boxShadow:'0 8px 32px rgba(3,2,12,0.6)',
    zIndex:500, whiteSpace:'nowrap', maxWidth:'90vw',
  }">
    <template v-if="type === 'limit'">
      <span style="font-family:var(--ff-body,'DM Sans',sans-serif);font-size:13px;color:rgba(255,91,108,0.9)">{{ message }}</span>
    </template>
    <template v-else>
      <KissesIcon :size="18" />
      <span style="font-family:var(--ff-display,'Unbounded',sans-serif);font-size:20px;color:#f5c560;font-weight:800">+{{ amount }}</span>
      <span v-if="multiplier && multiplier > 1" style="font-family:var(--ff-label,'Saira Condensed',sans-serif);font-size:10px;letter-spacing:0.15em;color:#6cf0e0;text-transform:uppercase">
        ×{{ multiplier.toFixed(1) }} streak {{ streakDays }}d
      </span>
    </template>
  </div>
</template>
