// src/components/swap/SwapCard.jsx
'use client';
import { useRef, useState } from 'react';
import { C, FF } from '@/app/gioco/_redesign/_shared';
import { ikUrl } from '@/lib/imagekitUrl';

const SWIPE_THRESHOLD = 80;

export default function SwapCard({ waifu, onVote }) {
  const cardRef = useRef(null);
  const startRef = useRef(null);
  const [offsetX, setOffsetX] = useState(0);
  const [leaving, setLeaving] = useState(null); // 'like' | 'dislike' | null

  const vote = (direction) => {
    if (leaving) return;
    setLeaving(direction);
    setTimeout(() => { onVote?.(direction); setLeaving(null); setOffsetX(0); }, 320);
  };

  const onPointerDown = (e) => { startRef.current = e.clientX; };
  const onPointerMove = (e) => {
    if (startRef.current === null) return;
    setOffsetX(e.clientX - startRef.current);
  };
  const onPointerUp = () => {
    if (startRef.current === null) return;
    if (offsetX > SWIPE_THRESHOLD) vote('like');
    else if (offsetX < -SWIPE_THRESHOLD) vote('dislike');
    else setOffsetX(0);
    startRef.current = null;
  };

  const rotation = (offsetX / 300) * 15;
  const likeOpacity = Math.min(offsetX / SWIPE_THRESHOLD, 1);
  const dislikeOpacity = Math.min(-offsetX / SWIPE_THRESHOLD, 1);

  if (!waifu) return null;

  return (
    <div style={{ position: 'relative', width: '100%', maxWidth: 340, margin: '0 auto' }}>
      <div
        ref={cardRef}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerLeave={onPointerUp}
        style={{
          position: 'relative', borderRadius: 22, overflow: 'hidden',
          aspectRatio: '3/4', cursor: 'grab', touchAction: 'none',
          transform: `translateX(${leaving ? (leaving === 'like' ? 400 : -400) : offsetX}px) rotate(${leaving ? (leaving === 'like' ? 25 : -25) : rotation}deg)`,
          transition: leaving ? 'transform 0.32s ease-in, opacity 0.32s' : 'transform 0.05s',
          opacity: leaving ? 0 : 1,
          boxShadow: '0 24px 60px rgba(3,2,12,0.7)',
          userSelect: 'none',
        }}
      >
        {/* Card image — ottimizzata con ikUrl (preset 'normal' per Swap: ~600px) */}
        {(waifu.asset_immagine || waifu.asset_statica || waifu.asset_immersiva) ? (
          <img
            src={ikUrl(waifu.asset_immagine || waifu.asset_statica || waifu.asset_immersiva, 'normal')}
            alt={waifu.nome}
            style={{ width: '100%', height: '100%', objectFit: 'cover', pointerEvents: 'none' }}
          />
        ) : (
          <div style={{ width: '100%', height: '100%', background: 'linear-gradient(180deg, #1b1638, #251f48)', display: 'grid', placeItems: 'center' }}>
            <span style={{ fontSize: 64, opacity: 0.3 }}>♛</span>
          </div>
        )}

        {/* Gradient bottom */}
        <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: '50%', background: 'linear-gradient(transparent, rgba(3,2,12,0.95))' }} />

        {/* Name */}
        <div style={{ position: 'absolute', bottom: 20, left: 18, right: 18 }}>
          <div style={{ fontFamily: FF.display, fontSize: 22, color: '#fff', fontWeight: 800 }}>{waifu.nome}</div>
          <div style={{ fontFamily: FF.label, fontSize: 10, letterSpacing: '0.2em', color: 'rgba(241,235,255,0.5)', textTransform: 'uppercase', marginTop: 3 }}>
            {waifu.rarita} · {waifu.tipo}
          </div>
        </div>

        {/* Like overlay */}
        <div style={{ position: 'absolute', top: 20, left: 20, opacity: likeOpacity, transform: 'rotate(-20deg)', transition: 'opacity 0.1s' }}>
          <div style={{ border: '4px solid #58e0a3', color: '#58e0a3', fontFamily: FF.display, fontSize: 28, fontWeight: 900, padding: '4px 12px', borderRadius: 8 }}>LIKE</div>
        </div>

        {/* Dislike overlay */}
        <div style={{ position: 'absolute', top: 20, right: 20, opacity: dislikeOpacity, transform: 'rotate(20deg)', transition: 'opacity 0.1s' }}>
          <div style={{ border: '4px solid #ff5b6c', color: '#ff5b6c', fontFamily: FF.display, fontSize: 28, fontWeight: 900, padding: '4px 12px', borderRadius: 8 }}>NOPE</div>
        </div>
      </div>

      {/* Action buttons */}
      <div style={{ display: 'flex', justifyContent: 'center', gap: 32, marginTop: 24 }}>
        <button onClick={() => vote('dislike')} style={actionBtn('#ff5b6c', 'rgba(255,91,108,0.12)')}>✕</button>
        <button onClick={() => vote('like')} style={actionBtn('#58e0a3', 'rgba(88,224,163,0.12)')}>♥</button>
      </div>
    </div>
  );
}

function actionBtn(color, bg) {
  return {
    width: 64, height: 64, borderRadius: '50%',
    background: bg, border: `2px solid ${color}55`,
    color, fontSize: 26, cursor: 'pointer',
    display: 'grid', placeItems: 'center',
    boxShadow: `0 4px 20px ${color}20`,
    transition: 'all 0.15s',
  };
}

// components/swap/SwapCard.vue
<!-- Carta waifu con swipe gesture per il sistema Swap (like/dislike) -->
<script setup lang="ts">
import { ikUrl } from '~/utils/imagekitUrl'

const props = defineProps<{
  waifu: Record<string, any>
  expansionName?: string | null
}>()
const emit = defineEmits<{ vote: [direction: 'like' | 'dislike'] }>()

const SWIPE_THRESHOLD = 80
const offsetX = ref(0)
const leaving = ref<'like' | 'dislike' | null>(null)
const startX = ref<number | null>(null)

const rotation = computed(() => (offsetX.value / 300) * 15)
const likeOpacity = computed(() => Math.min(offsetX.value / SWIPE_THRESHOLD, 1))
const dislikeOpacity = computed(() => Math.min(-offsetX.value / SWIPE_THRESHOLD, 1))

const cardTransform = computed(() => {
  if (leaving.value) {
    const tx = leaving.value === 'like' ? 400 : -400
    const rot = leaving.value === 'like' ? 25 : -25
    return `translateX(${tx}px) rotate(${rot}deg)`
  }
  return `translateX(${offsetX.value}px) rotate(${rotation.value}deg)`
})
const cardTransition = computed(() =>
  leaving.value ? 'transform 0.32s ease-in, opacity 0.32s' : 'transform 0.05s'
)
const cardOpacity = computed(() => leaving.value ? 0 : 1)

function vote(direction: 'like' | 'dislike') {
  if (leaving.value) return
  leaving.value = direction
  setTimeout(() => {
    emit('vote', direction)
    leaving.value = null
    offsetX.value = 0
  }, 320)
}

function onPointerDown(e: PointerEvent) { startX.value = e.clientX }
function onPointerMove(e: PointerEvent) {
  if (startX.value === null) return
  offsetX.value = e.clientX - startX.value
}
function onPointerUp() {
  if (startX.value === null) return
  if (offsetX.value > SWIPE_THRESHOLD) vote('like')
  else if (offsetX.value < -SWIPE_THRESHOLD) vote('dislike')
  else offsetX.value = 0
  startX.value = null
}

const imageUrl = computed(() => {
  const src = props.waifu?.asset_immagine || props.waifu?.asset_statica || props.waifu?.asset_immersiva
  return src ? ikUrl(src, 'normal') : null
})

function actionBtn(color: string, bg: string) {
  return { width:'64px', height:'64px', borderRadius:'50%', background:bg, border:`2px solid ${color}55`, color, fontSize:'26px', cursor:'pointer', display:'grid', placeItems:'center', boxShadow:`0 4px 20px ${color}20`, transition:'all 0.15s' }
}
</script>

<template>
  <div v-if="waifu" style="position:relative;width:100%;max-width:340px;margin:0 auto">
    <div
      :style="{
        position:'relative', borderRadius:'22px', overflow:'hidden',
        aspectRatio:'3/4', cursor:'grab', touchAction:'none',
        transform: cardTransform,
        transition: cardTransition,
        opacity: cardOpacity,
        boxShadow:'0 24px 60px rgba(3,2,12,0.7)',
        userSelect:'none',
      }"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      @pointerleave="onPointerUp"
    >
      <img
        v-if="imageUrl"
        :src="imageUrl"
        :alt="waifu.nome"
        style="width:100%;height:100%;object-fit:cover;pointer-events:none"
      />
      <div v-else style="width:100%;height:100%;background:linear-gradient(180deg,#1b1638,#251f48);display:grid;place-items:center">
        <img src="~/assets/images/Logo.png" alt="" style="width:80px;height:80px;object-fit:contain;opacity:0.82;" />
      </div>

      <div style="position:absolute;bottom:0;left:0;right:0;height:50%;background:linear-gradient(transparent,rgba(3,2,12,0.95))" />

      <div style="position:absolute;bottom:20px;left:18px;right:18px">
        <div style="font-family:var(--ff-display,'Unbounded',sans-serif);font-size:22px;color:#fff;font-weight:800">{{ waifu.nome }}</div>
        <div style="font-family:var(--ff-label,'Saira Condensed',sans-serif);font-size:10px;letter-spacing:0.2em;color:rgba(241,235,255,0.5);text-transform:uppercase;margin-top:3px">
          {{ waifu.rarita }} · {{ waifu.tipo }}
          <span v-if="expansionName" style="color:rgba(174,156,255,0.6);margin-left:6px">· {{ expansionName }}</span>
        </div>
      </div>

      <div :style="{ position:'absolute', top:'20px', left:'20px', opacity:likeOpacity, transform:'rotate(-20deg)', transition:'opacity 0.1s' }">
        <div style="border:4px solid #58e0a3;color:#58e0a3;font-family:var(--ff-display);font-size:28px;font-weight:900;padding:4px 12px;border-radius:8px">LIKE</div>
      </div>
      <div :style="{ position:'absolute', top:'20px', right:'20px', opacity:dislikeOpacity, transform:'rotate(20deg)', transition:'opacity 0.1s' }">
        <div style="border:4px solid #ff5b6c;color:#ff5b6c;font-family:var(--ff-display);font-size:28px;font-weight:900;padding:4px 12px;border-radius:8px">NOPE</div>
      </div>
    </div>

    <div style="display:flex;justify-content:center;gap:32px;margin-top:24px">
      <button @click="vote('dislike')" :style="actionBtn('#ff5b6c','rgba(255,91,108,0.12)')">✕</button>
      <button @click="vote('like')" :style="actionBtn('#58e0a3','rgba(88,224,163,0.12)')">♥</button>
    </div>
  </div>
</template>
